### ISSUE TITLE
Emphasis with underscore

### ISSUE THREAD

**Issue by aduh95** [markedjs/marked#1010]
## Expectation

[CommonMark Playground link](http://spec.commonmark.org/dingus/?text=%23%20Hello%0A%0AHere%20is%20some%20emphasis%3A%20_Hello_World_%0A%0ADone.%0A)

```html
<h1>Hello</h1>
<p>Here is some emphasis: <em>Hello_World</em>!</p>
<p>Done.</p>
```

## Result

```html
<h1 id="hello">Hello</h1>
<p>Here is some emphasis: _Hello<em>World</em>!</p>
<p>Done.</p>
```

## What was attempted

```markdown
# Hello

Here is some emphasis: _Hello_World_!

Done.
```

I've found [an example in the CommonMark spec](http://spec.commonmark.org/0.28/#example-356)  describing this very behavior.

**Comment by Feder1co5oave** [comment]
Thanks for reporting this, it looks like it is really broken. I'm not keen on changing the `em` regex since it changed quite a lot of times in the past and it looks really awful now.
Moreover, that commonmark spec for emphasis really is **hell**!
I think the usual approach to make emphasis work with underscores in it is to double the delimiting underscores:

```markdown
$ bin/marked
# Hello!

Here is some emphasis: __Hello_World__!

Done.
```

~~~html
<h1 id="hello-">Hello!</h1>
<p>Here is some emphasis: <strong>Hello_World</strong>!</p>
<p>Done.</p>
~~~

**Comment by aduh95** [comment]
Thank you for your help. I am aware of this workaround, but my team uses [Prettier](https://prettier.io/) formatter for our documents. It is a great tool to have an unified syntax, unfortunately it is a pain in the neck for this particular issue, because it automatically replaces the star delimiters with underscores.

**Comment by joshbruce** [comment]
Interesting. Just to make sure I'm understanding, without getting too into the weeds: Prettier essentially "transpiles," for lack of a better term, asterisks into underscores. Then *that's* the result you are displaying?

I guess I'm trying to see the flow of data, from a user perspectvie, at a high-level:

User -> Markdown -> Marked -> Prettier -> display

??

**Comment by aduh95** [comment]
Yes, pretty much, you can observe it on their [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABACTgGxxAHSiOwCc50BLAZ3WogFsLKYBDHSsJdAKmzwgB9AOoRSOACY8ScclVr0m6BmLjdB-fAQIixkwUSIARaHAB0REABoQEAA4xK0aslCtSpCAHcACu4QuKKwAbhCUEtYgrNQwyABm7NRwNgBGpKxgANZwMADKdhmUUADmyDCkAK7JIBIQYPGJ1UVJpDA+6cUMrA04STYAVtQAHgBC6Vk5uaxMADJFcD19thUwdisATIvVBaQtyCBdpJm1XlCRdqRFMMLhMAAWyAAcAAw2FxBJwul2+xdwLcEFjZyABHCqUcjtVidbpIBK9apJBiUMqVRFFYo4OAARQqEHgWxsbBSNwk92Q6yJ6UoHBKAGFGF19lBTJEKkkACqsFKBeFJAC+-KAA). Every time we save a file on our editor, Prettier "transpiles" the file (adding spaces into tables to make them look like actual tables, replacing asterisks into underscores for emphasis, etc.) which then is used by Marked for displaying.

The flow of data is more like that:

User -> Markdown -> Prettier -> Marked -> display

**Comment by joshbruce** [comment]
@aduh95: Gotcha, I'm going to convert this to a new feature for now because it's more of an integration issue, and trust @Feder1co5oave when he says it's still broken. Thanks.

(As you can tell by the changes in the ticket types, I had an internal battle on where exactly to put it.) :)

**Comment by UziTech** [comment]
looks like this is fixed in the latest version. [demo](https://marked.js.org/demo/?outputType=html&text=%23%20Hello%0A%0AHere%20is%20some%20emphasis%3A%20_Hello_World_%0A%0ADone.%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20false%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)
