### ISSUE TITLE
grammar for inline codes is not good

### ISSUE THREAD

**Issue by icecola2018** [markedjs/marked#1052]
## Expectation

~~~
``foo

foo``

`foo``

``foo`
~~~

should be

~~~html
<p>foo``</p>
<p>``foo</p>
<p>`foo``</p>
<p>``foo`</p>
~~~

## Result
**_marked_** returns
~~~html
<p><code></code>foo</p>
<p>foo<code></code></p>
<p><code>foo`</code></p>
<p><code></code>foo`</p>
~~~

## What was attempted

I edited _marked.js_:

1. **line 471**, replace ``code: /^(`+)(\s*)([\s\S]*?[^`]?)\2\1(?!`)/`` with ``code: /^(`+(?!`))([\s\S]*?[^`])\1(?!`)/``
2. **line 694**, replace `cap[3]` with `cap[2]`

then get
~~~html
<p>foo``</p>
<p>``foo</p>
<p>`foo``</p>
<p>`<code>foo</code></p>
~~~

However it doesn't work well on the last one.

**Comment by Feder1co5oave** [comment]
Thanks for reporting, this was partially my mistake in #1013.

[Babelmark](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%60%60foo%0A%0Afoo%60%60%0A%0A%60foo%60%60%0A%0A%60%60foo%60) for reference.

The fix you suggest brings us back before #1013 so it is not right.
I have an easy partial fix for this which would produce the following output:
```html
<p>``foo</p>
<p>foo``</p>
<p>`foo``</p>
<p><code>`foo</code></p>
```
I'm adding this to the consolidating issue hoping that we'll conform with commonmark on codespans too.

**Comment by icecola2018** [comment]
Reply to @Feder1co5oave 

I see the problem in #1030 .

Actually my suggestion
```
/^(`+(?!`))([\s\S]*?[^`])\1(?!`)/
```
is different from the one before #1030
```
/^(`+)([\s\S]*?[^`])\1(?!`)/
```

-----

I found that back references (such as `\1`) perform strangely when they refer to groups ending with `+` or `*`. In fact `\1` has chance to match any quantities of `` ` ``.

For example, if `` (`+) `` matched ` `` ` and it was not closed, then `\1` would match `` ` `` or ` ``` ` or ` ```` ` or ...
That's why `` /^(`+)([\s\S]*?[^`])\1(?!`)/ `` works well on ``` `` ` `` ``` but wrong on ```` `` ` ``` ````.

-----

Then I added `` (?!`) `` after `+` to the first group, which seemed no sense. Actually it worked well, `\1` will only match the same string that the group matches. You may test it to be sure.

-----

I'm not very good at English, so I will try my best to explain if you don't understand what I want to say.

**Comment by Feder1co5oave** [comment]
Thanks, you've been very clear and detailed, I'll look into this!

**Comment by UziTech** [comment]
this seems to be fixed in the latest version of marked [demo](https://marked.js.org/demo/?outputType=html&text=%60%60foo%0A%0Afoo%60%60%0A%0A%60foo%60%60%0A%0A%60%60foo%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)
