### ISSUE TITLE
Nasty list parsing edge case

### ISSUE THREAD

**Issue by vsemozhetbyt** [markedjs/marked#1180]
See https://github.com/nodejs/node/pull/19647

The list item number in v0.3.6 is `1`, in v0.3.19 is `0`, but the erroneous list is added in both cases, unlike the GitHub parser behavior.

**Comment by styfle** [comment]
I was able to reproduce with this:

```
Example list that does not work.

* First one goes here. We can add a new line here as long as we indent
  and the output will render as if there is no new line.
* But if we start the next line with a number followed by a period such as
  0. Then it will not render properly.

Example list that does work.

* First one goes here. We can add a new line here as long as we indent
  and the output will render as if there is no new line.
* Now if we start the next line to end with a number followed by a period such as 0.
  Then it will render properly.
```

[Marked Demo](https://marked.js.org/demo/?text=Example%20list%20that%20does%20not%20work.%0A%0A*%20First%20one%20goes%20here.%20We%20can%20add%20a%20new%20line%20here%20as%20long%20as%20we%20indent%0A%20%20and%20the%20output%20will%20render%20as%20if%20there%20is%20no%20new%20line.%0A*%20But%20if%20we%20start%20the%20next%20line%20with%20a%20number%20followed%20by%20a%20period%20such%20as%0A%20%200.%20Then%20it%20will%20not%20render%20properly.%0A%0AExample%20list%20that%20does%20work.%0A%0A*%20First%20one%20goes%20here.%20We%20can%20add%20a%20new%20line%20here%20as%20long%20as%20we%20indent%0A%20%20and%20the%20output%20will%20render%20as%20if%20there%20is%20no%20new%20line.%0A*%20Now%20if%20we%20start%20the%20next%20line%20to%20end%20with%20a%20number%20followed%20by%20a%20period%20such%20as%200.%0A%20%20Then%20it%20will%20render%20properly.)

I haven't looked at the spec but it seems like this is ambigous behavior since nested lists are possible.
