### ISSUE TITLE
Incorrect parsing for the case with numbered and bullet lists

### ISSUE THREAD

**Issue by ivankarpey** [markedjs/marked#1191]
**Version** 0.3.19

**Flavour** gfm

**markdown:**

```
This is some problem header

This is second paragraph

1.  one
2.  two

*   p1
*   p2

> cit
```

**expected:**

```
<p>This is some problem header</p>
<p>This is second paragraph</p>
<ol>
<li>one</li>
<li>two</li>
</ol>
<ul>
<li>p1</li>
<li>p2</li>
</ul>
<blockquote>
<p>cit</p>
</blockquote>
```

**marked output:**

```
<p>This is some problem header</p>
<p>This is second paragraph</p>
<ol>
<li>one</li>
<li><p>two</p>
</li>
<li><p>p1</p>
</li>
<li>p2</li>
</ol>
<blockquote>
<p>cit</p>
</blockquote>
```

**Comment by UziTech** [comment]
looks like this was fixed in v0.6.0 [demo](https://marked.js.org/demo/?text=This%20is%20some%20problem%20header%0A%0AThis%20is%20second%20paragraph%0A%0A1.%20%20one%0A2.%20%20two%0A%0A*%20%20%20p1%0A*%20%20%20p2%0A%0A%3E%20cit&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.6.0)
