### ISSUE TITLE
Dependents active??

### ISSUE THREAD

**Issue by joshbruce** [markedjs/marked#1215]
**Marked version:** 0.3.19

**Markdown flavor:** n/a

**Proposal type:** other

## What pain point are you perceiving?

3,000+ dependents...really??

## What solution are you suggesting?

An automated way to iterate over the list of dependents. See what version they are using and when they last published to NPM. Hypothesis: Many of those packages are not active, reference Marked as prior art, or have a small audience base. 

Tagging @UziTech, @styfle, and @Martii

See also #1123

**Comment by styfle** [comment]
You can [page through all 3000 dependendents](https://www.npmjs.com/browse/depended/marked).

But it doesn't look like there is any particular order.

@joshbruce What would we consider inactive? No downloads in the last 30 days?

**Comment by joshbruce** [comment]
@UziTech: ::sad trombone:: 

```
error getting dependents for [marked] { Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443

error getting dependents for [marked] Error: Invalid JSON (Unexpected "h" at position 1 in state STOP)
```

@styfle: I don't know what constitutes active, to be honest, and it's a fair question. Think I'm mainly looking for ways to even start gathering the data easily on the dependents. In some cases, paging through, the publish date would be a good first start (some were published in the last week). npm/npm is easy because they specify a version number and "give credit" when they update; so, we get notified that they're still active and actively using (aware of) Marked.

**Comment by UziTech** [comment]
@joshbruce the errors are from sending too many requests to the npm rest api. There has to be two requests per dependent. I am working on a way to fix that ... stay tuned

**Comment by UziTech** [comment]
Here is a distribution of the version numbers:

```
[
  [
    594,
    "^0.3.6"
  ],
  [
    450,
    "^0.3.5"
  ],
  [
    218,
    "^0.3.2"
  ],
  [
    182,
    "^0.3.3"
  ],
  [
    103,
    "~0.3.2"
  ],
  [
    77,
    "*"
  ],
  [
    76,
    "0.3.6"
  ],
  [
    59,
    "0.3.5"
  ],
  [
    54,
    "^0.3.9"
  ],
  [
    51,
    "^0.3.12"
  ],
  [
    49,
    "~0.2.9"
  ],
  [
    40,
    "0.3.2"
  ],
  [
    37,
    "~0.3.1"
  ],
  [
    35,
    "^0.3.7"
  ],
  [
    35,
    "0.2.x"
  ],
  [
    34,
    "~0.2.8"
  ],
  [
    31,
    "0.3.x"
  ],
  [
    30,
    "^0.3.17"
  ],
  [
    29,
    "~0.2.10"
  ],
  [
    23,
    "~0.3.5"
  ],
  [
    23,
    "~0.3.0"
  ],
  [
    23,
    "~0.3.3"
  ],
  [
    21,
    "^0.3.19"
  ],
  [
    21,
    "0.3.9"
  ],
  [
    20,
    "0.3.3"
  ],
  [
    18,
    "~0.2.5"
  ],
  [
    18,
    ">= 0.2.7"
  ],
  [
    17,
    "~0.3.6"
  ],
  [
    13,
    "0.2.9"
  ],
  [
    12,
    "latest"
  ],
  [
    12,
    "0.2.8"
  ],
  [
    9,
    "^0.3.16"
  ],
  [
    9,
    ""
  ],
  [
    9,
    "~0.3.9"
  ],
  [
    8,
    "0.3.12"
  ],
  [
    7,
    "0.2.5"
  ],
  [
    7,
    "0.3.0"
  ],
  [
    7,
    "^0.3.18"
  ],
  [
    6,
    "0.3.1"
  ],
  [
    6,
    ">=0.2.9"
  ],
  [
    6,
    "~0.2.7"
  ],
  [
    6,
    ">=0.2.5"
  ],
  [
    5,
    "~0.2.6"
  ],
  [
    5,
    "^0.3.4"
  ],
  [
    5,
    "0.3.*"
  ],
  [
    4,
    "^0.3.14"
  ],
  [
    4,
    "0.1.x"
  ],
  [
    4,
    "~0.3"
  ],
  [
    4,
    "0.2.6"
  ],
  [
    3,
    "~0.1.9"
  ],
  [
    3,
    "^0.2.10"
  ],
  [
    3,
    "^0.3.15"
  ],
  [
    3,
    "0.3.17"
  ],
  [
    3,
    ">=0.3.5"
  ],
  [
    3,
    "^0.3.0"
  ],
  [
    3,
    "https://github.com/mrpotes/marked/tarball/html-structure"
  ],
  [
    3,
    "x"
  ],
  [
    3,
    "0.2.7"
  ],
  [
    2,
    "~0.2.4"
  ],
  [
    2,
    "^0.x"
  ],
  [
    2,
    "0.2.4"
  ],
  [
    2,
    "=0.3.2"
  ],
  [
    2,
    "=0.2.5"
  ],
  [
    2,
    ">= 0.2.5"
  ],
  [
    2,
    ">=0.1.2"
  ],
  [
    2,
    ">= 0.2.9"
  ],
  [
    2,
    "~0.3.17"
  ],
  [
    2,
    "~0.3.7"
  ],
  [
    2,
    "~0.2"
  ],
  [
    2,
    "~0.2.x"
  ],
  [
    2,
    "0.2.10"
  ],
  [
    2,
    "^0.3"
  ],
  [
    2,
    ">=0.2.8"
  ],
  [
    2,
    ">=0.2.10"
  ],
  [
    1,
    "0.3.4"
  ],
  [
    1,
    "0.0.4"
  ],
  [
    1,
    "0"
  ],
  [
    1,
    "~x.x.x"
  ],
  [
    1,
    "https://github.com/akira-cn/marked/tarball/gitpress"
  ],
  [
    1,
    ">= 0.2.10"
  ],
  [
    1,
    ">=0.0.0"
  ],
  [
    1,
    "0.3.19"
  ],
  [
    1,
    ">= 0.1.7"
  ],
  [
    1,
    "0.3"
  ],
  [
    1,
    ">= 0.2.8"
  ],
  [
    1,
    ">=0.3.0"
  ],
  [
    1,
    "^0.3.1"
  ],
  [
    1,
    ">= 0.2.6"
  ],
  [
    1,
    "~0.3.4"
  ],
  [
    1,
    "~0.3.x"
  ],
  [
    1,
    ">=0.2.6"
  ],
  [
    1,
    "~0.3.19"
  ],
  [
    1,
    "~0.3.16"
  ],
  [
    1,
    "github:rumkin/marked"
  ],
  [
    1,
    ">= 0.3.3"
  ],
  [
    1,
    ">= 0.2.4-1"
  ],
  [
    1,
    ">= 0.3.5"
  ],
  [
    1,
    "git://github.com/twinlabs/marked.git"
  ],
  [
    1,
    "http://registry.npmjs.org/marked/-/marked-0.3.2.tgz"
  ],
  [
    1,
    ">= 0.1.9"
  ],
  [
    1,
    "~0.1.6"
  ],
  [
    1,
    "git://github.com/chjj/marked.git"
  ],
  [
    1,
    "git://github.com/chjj/marked.git#master"
  ],
  [
    1,
    "git+https://github.com/crazyguitar/marked.git"
  ],
  [
    1,
    ">=0.3.3"
  ],
  [
    1,
    "git://github.com/mgutz/marked"
  ],
  [
    1,
    "^0.2.8"
  ],
  [
    1,
    ">=0.3.2"
  ],
  [
    1,
    "== 0.2.5"
  ],
  [
    1,
    ">0.2.4"
  ],
  [
    1,
    "0.2.3"
  ],
  [
    1,
    "github:rhysd/marked#emoji"
  ],
  [
    1,
    "git://github.com/clehner/marked#8af8ae018ba452b5c7f936a474dbce265f2ae732"
  ],
  [
    1,
    ">= 0.3.0"
  ],
  [
    1,
    "0.2.109"
  ],
  [
    1,
    "=0.3.3"
  ],
  [
    1,
    ">=0.1.4"
  ],
  [
    1,
    "0.3.18"
  ],
  [
    1,
    "git+https://github.com/chester1000/marked.git"
  ],
  [
    1,
    "git://github.com/jnordberg/marked.git"
  ],
  [
    1,
    "0.3.16"
  ],
  [
    1,
    "git+https://github.com/davitv/marked.git"
  ],
  [
    1,
    "0.0.1"
  ],
  [
    1,
    "0.x"
  ],
  [
    1,
    ">=0.2.10 <0.3"
  ]
]
```

**Comment by UziTech** [comment]
I created a [repo](https://github.com/UziTech/marked-dependents) with the code I used to get the dependency info and some [stats](https://github.com/UziTech/marked-dependents/tree/master/stats)

**Comment by styfle** [comment]
@UziTech Very cool!

One thing to improve the results is to interpret the semver to see which version would be downloaded if they installed today.

For example,

- `^0.3.6` `^0.3.3` `^0.3.5` `^0.3.2` would actually install `0.3.19` today since that's the latest of the 0.3.x line.
- `~0.3.2` would actually install `0.3.19`
- '*' would actually install `0.3.19`

Can you aggregate the version that would be installed, not the literal string in the package.json?

**Comment by joshbruce** [comment]
@UziTech: That's pretty awesome. I took a look at the repo and, honestly, it landed somewhere between my own ignorance and "I just woke up". How much of the output can we tailor? What are the ids (they don't seem to be unique as there are multiple 7s, for example)? Can/Should we move that repo to the Marked org?

**Comment by UziTech** [comment]
> What are the ids

What ids?

> Can/Should we move that repo to the Marked org?

Ya that would be fine. This was just my quick PoC to check if we could/how to get info about our dependents.

If this is going to be something we actually want to use to keep track of our dependents, we should come up with some metrics that we want to make visible and I could show those metrics on the readme.md and update it every week or so.

Currently because of npm's api request throttling it takes about 2 minutes to get all the dependents info.

**Comment by UziTech** [comment]
That is not the id, that is the number of dependents that use that version.

The [packages](https://github.com/UziTech/marked-dependents/tree/master/packages) folder is where I save all dependents info:

```json
{
	"name": "Antony",
	"version": "0.3.0",
	"depVersion": "^0.3.6",
	"maintainers": [
		{
			"name": "spiral",
			"email": "scriptAntony@163.com"
		}
	],
	"modified": "2016-09-09T16:27:48.031Z",
	"released": "2016-09-09T16:27:48.031Z",
	"downloadsLastWeek": 2
}
```

**Comment by joshbruce** [comment]
@styfle: Think we're almost there.

@UziTech: Would it be possible to put the repo under the MarkedJS org? Maybe also provide a README on how to run it?

**Comment by styfle** [comment]
This page provides some valuable insights https://libraries.io/npm/marked/usage

**Comment by Martii** [comment]
That's interesting... it' polling OUJS GH dev *(so GH in general)*. Kewl.

**Comment by styfle** [comment]
@Martii Let's see if they respond on [twitter](https://twitter.com/styfle/status/1011755308811681792) 🤷‍♂️ 

Here's [^0.4.0](https://libraries.io/npm/marked/usage?requirements=%5E0.4.0) and exact [0.4.0](https://libraries.io/npm/marked/usage?requirements=0.4.0)

**Comment by uk1free** [comment]
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Steven <notifications@github.com> Date: 27/06/2018  00:39  (GMT+00:00) To: markedjs/marked <marked@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [markedjs/marked] Dependents active?? (#1215) 
@Martii Let's see if they respond on twitter 🤷‍♂️
Here's ^0.4.0 and exact 0.4.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/markedjs/marked","title":"markedjs/marked","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/markedjs/marked"}},"updates":{"snippets":[{"icon":"PERSON","message":"@styfle in #1215: @Martii Let's see if they respond on [twitter](https://twitter.com/styfle/status/1011755308811681792) 🤷‍♂️ \r\n\r\nHere's [^0.4.0](https://libraries.io/npm/marked/usage?requirements=%5E0.4.0) and exact [0.4.0](https://libraries.io/npm/marked/usage?requirements=0.4.0)"}],"action":{"name":"View Issue","url":"https://github.com/markedjs/marked/issues/1215#issuecomment-400496357"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/markedjs/marked/issues/1215#issuecomment-400496357",
"url": "https://github.com/markedjs/marked/issues/1215#issuecomment-400496357",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [markedjs/marked] Dependents active?? (#1215)",
"sections": [
{
"text": "",
"activityTitle": "**Steven**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@styfle",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"markedjs/marked\",\n\"issueId\": 1215,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"markedjs/marked\",\n\"issueId\": 1215\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/markedjs/marked/issues/1215#issuecomment-400496357"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 323554383\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by uk1free** [comment]
M

http://texthelpdemo.speechstream.net/texthelpdemo/CustomUI.htm




Sent from my Samsung Galaxy smartphone.

**Comment by joshbruce** [comment]
Deleting @uk1free comment as off topic.

**Comment by styfle** [comment]
> Let's see if they [libraries.io] respond on twitter 

It must be somewhat often because they have [^0.5.0](https://libraries.io/npm/marked/usage?requirements=%5E0.5.0) and [0.5.0](https://libraries.io/npm/marked/usage?requirements=0.5.0) listed already.

@UziTech @joshbruce Do we still want to move [UziTech/marked-dependents](https://github.com/UziTech/marked-dependents) under the markedjs org on GitHub?

**Comment by UziTech** [comment]
I transfered ownership of [marked-dependents](https://github.com/markedjs/marked-dependents)

**Comment by styfle** [comment]
Excellent! 🎉 
I'll close this issue 😄
