### ISSUE TITLE
Bug: not resolve table when use <details>

### ISSUE THREAD

**Issue by gozeon** [markedjs/marked#1263]
See [demo](https://marked.js.org/demo/?text=%3Cdetails%3E%0A%3Csummary%3E%20The%20bug%20for%20details%20%26%20table%20%3C%2Fsummary%3E%0A%0AFirst%20Header%20%7C%20Second%20Header%0A------------%20%7C%20-------------%0AContent%20from%20cell%201%20%7C%20Content%20from%20cell%202%0AContent%20in%20the%20first%20column%20%7C%20Content%20in%20the%20second%20column%0A%0A%3C%2Fdetails%3E%0A)

**Comment by styfle** [comment]
Hi @gozeon, thanks for the bug report!

Looks like this problem is more than just tables.

Here's the same bug with a heading:

```
<details>
<summary> The bug for details & table </summary>

# Heading

</details>
```

[marked](https://marked.js.org/demo/?text=%3Cdetails%3E%0A%3Csummary%3E%20The%20bug%20for%20details%20%26%20table%20%3C%2Fsummary%3E%0A%0A%23%20Heading%0A%0A%3C%2Fdetails%3E%0A)

[commonmark](https://spec.commonmark.org/dingus/?text=%3Cdetails%3E%0A%3Csummary%3E%20The%20bug%20for%20details%20%26%20table%20%3C%2Fsummary%3E%0A%0A%23%20Heading%0A%0A%3C%2Fdetails%3E%0A)
