### ISSUE TITLE
Don't Encode Internationalized Domain Names

### ISSUE THREAD

**Issue by ilyaigpetrov** [markedjs/marked#1285]
**What pain point are you perceiving?.**
```sh-session
$ npx marked
[aaa](https://сл96.рф)   
<p><a href="https://%D1%81%D0%BB96.%D1%80%D1%84">aaa</a></p>
```
`require('url').parse('https://%D1%81%D0%BB96.%D1%80%D1%84')` populates `pathname` instead of `hostname`:
```js
Url {
  protocol: 'https:',
  slashes: true,
  auth: null,
  host: '',
  port: null,
  hostname: '',
  hash: null,
  search: null,
  query: null,
  pathname: '%D1%81%D0%BB96.%D1%80%D1%84',
  path: '%D1%81%D0%BB96.%D1%80%D1%84',
  href: 'https:///%D1%81%D0%BB96.%D1%80%D1%84' }
```
**Describe the solution you'd like**
Please, don't percent-encode internationalized domain names, because it doesn't work well with `url.parse`. I see no reason for IDN to be encoded.

**Comment by UziTech** [comment]
Looks like we would need to extract the domain name from `href` in `Renderer.prototype.link`

https://github.com/markedjs/marked/blob/ac4f2e46ee75b8bc23a336d0e79fe8fa65f55476/lib/marked.js#L1015

A PR would be welcome

**Comment by styfle** [comment]
FYI, it looks like [CommonMark](https://spec.commonmark.org/dingus/?text=%5Baaa%5D(https%3A%2F%2F%D1%81%D0%BB96.%D1%80%D1%84)%20%20) has the same behavior as [marked](https://marked.js.org/demo/?outputType=html&text=%5Baaa%5D(https%3A%2F%2F%D1%81%D0%BB96.%D1%80%D1%84)%20%20).

@UziTech How would you safely extract the domain name? Maybe something like this?

```js
function getHostName() {
  var url = new URL(href);
  return url.hostname
}
```

But this relies on `URL` which is not available in IE.

**Comment by Martii** [comment]
Perhaps https://nodejs.org/api/url.html#url_url_format_url_options could be of help.... although use all `true` values since we would want those available. I'm not entirely sure why this project is encoding without diving into the historical commits.

**Comment by UziTech** [comment]
@Martii marked is used on the client side as well and in Node so Node APIs won't work.

@styfle We could just use regex

```js
function getHostName(href) {
  return href.match(/^https?:\/\/[^\/]+\//)[0];
}
```

**Comment by ilyaigpetrov** [comment]
Why do you need to encode and then to escape:
```js
href = encodeURI(href).replace(/%25/g, '%');
var out = '<a href="' + escape(href) + '"';
```
What's the purpose? Can't you just do this instead:
```js
href = href.replace(/"/g, '%22');
var out = '<a href="' + href + '"';
```

**Comment by ilyaigpetrov** [comment]
Also it may be not a marked fault, but a fault of `url` module of Node.js, because Chrome and `new URL(href)` both handle percent-encoded IDNs just fine.

**Comment by ilyaigpetrov** [comment]
After a little contemplation I decided I'm fine with the current behavior as long as it works in major browsers and handled by search engines. If you agree and don't see any problem with `url` Node.js module then you may close it.

**Comment by styfle** [comment]
> Would be nice if ECMAScript standards would incorporate some sort of improved IRI handling like this.

@Martii There is the [WHATWG URL](https://nodejs.org/api/url.html#url_the_whatwg_url_api) standard which is implemented in modern browsers and newer versions of Node.js which I believe has improved IRI handling. See [my comment](https://github.com/markedjs/marked/issues/1285#issuecomment-394482945) above.

> After a little contemplation I decided I'm fine with the current behavior as long as it works in major browsers and handled by search engines. If you agree and don't see any problem with url Node.js module then you may close it.

@ilyaigpetrov Thanks, I'll close this issue.

**Comment by AlynxZhou** [comment]
Hi, I am using marked.js to build my own static site generator, and I found this issue, which breaks my code.

I use my own implementation to convert all links to absolute path and encode them, yesterday I found marked.js do encode again so the link is wrong after encode twice. I cannot stop doing encode in my code because not all pages are generated via marked.js (tags cloud, categories...). I read this issue and have some questions:

- In <https://github.com/markedjs/marked/issues/1285#issuecomment-394482945>, I am not sure why marked needs to extract host name from URL, I think converting `[aaa](bbb)` into `<a href="bbb">aaa</a>`  does not need to know what `bbb` means.
- If extracting host name is needed by some [options](https://marked.js.org/using_advanced#options) (maybe `baseUrl` I guess? to know whether we need to add prefix?), could you please skip doing encode if user does not enable this option? For example my code does not use it, because I have my own function to add base URL for all relative links in my site.

**Comment by UziTech** [comment]
@AlynxZhou marked tries to follow [CommonMark spec](https://spec.commonmark.org/0.30/#links) I think you will have to change the spec if you want this changed in marked. Otherwise you can create an [extension](https://marked.js.org/using_pro#extensions) for marked that people can use that does not encode urls. We want to stay away from adding more options to marked to prevent [feature creep](https://developerexperience.io/problems/unnecessary-features).
