### ISSUE TITLE
New release (Please?)

### ISSUE THREAD

**Issue by robcresswell** [markedjs/marked#1321]
**What pain point are you perceiving?.**
Many bugfixes / features added since last release
 
**Describe the solution you'd like**
It would be good to see more frequent releases. I know there is a sense of trying to make each release bug-free etc, but it would be great to be able to consume the complete fixes a bit more readily. Currently the delay between releases is several months / triple-figure commits; this also raises the risk of new bugs being added but not found via real world usage.

**Comment by joshbruce** [comment]
Thank you for submitting a request to do a release! Think this is the first time someone from outside of the core team has done so (even though someone inside the core team did ask yesterday in PR). :)

We try to prioritize pull from outside the core team - then the pull from within the core team. So, again, thank you.

Release will be coming out today, was discussed in some of the most recent PRs (yesterday).

***

Not sure I agree with the assessment on frequency of releases. For the most part, since we started the revival, we've had a release every month. Near as I can tell, 0.5.0 has been the longest gap between releases, which is only 3 months. With double-digit commits, not triple...some of which are documentation updates.

It's not the frequency of releases, it's what's changed, imho.

This release has no security or bug fixes, which tend to take the urgency piece. The fixes are mainly related to spec compliance.

Not saying something won't change, just giving my observation. 

If we get more contributors fixing more of the spec compliance issues then we will probably see more frequent releases. There's 4 of us on the core team and, for the most part and to be honest, we're more focused on making things run smoothly and handling our day jobs. The submissions of users looking to fix spec compliance have been wonderful, but I don't think we've really been flooded with them.

cc: @styfle, @UziTech, @davisjam - Thoughts? Think I'm off somewhere.

**Comment by robcresswell** [comment]
@joshbruce Maybe I'm missing something, but it looks like 0.4.0 was ~3 months and 80+ commits ago, before that 0.3.19 was small, 0.3.18 was 200+ commits and 3 months, 0.3.17 was again 150+ and 2 months. Numbers aside, there's good work going on, which I really appreciate and it would be great to be able to use it.

The main fix / feature I was looking for here was the empty cell handling in tables :smile:

**Comment by joshbruce** [comment]
Part of the disconnect might be language. I tend to look at "several" as being more than 4. 2 is a "couple". 4 is a "few". So, we tend to have a release every couple of months - not several. 😉

Commits can be a red herring - I can completely rewrite Marked in one commit. I could change one line with 50 commits. 😀

That's why I tend to only look at the release notes. Much more realistic representation of what's going on.

I'm glad you're appreciating what we and the contributors are doing and it looks like we timed it just right again...pull (desire) finally hit a point for someone to say something right at the time we were going to do something. Woohoo!
