### ISSUE TITLE
Markdown mixed bold / italic parsed incorrectly

### ISSUE THREAD

**Issue by Havunen** [markedjs/marked#1353]
**Describe the bug**
Marked parses mixed bold and italic incorrectly

**To Reproduce**

Link to [editor](https://marked.js.org/demo/?text=%23%20This%20is%20bug%20report%0A%0AI%20want%20to%20style%20word%20emphasis%20so%20that%20first%203%20characters%20are%20bold%20and%20last%203%20characters%20are%20bold%0A%0AThen%20from%20the%20second%20first%20character%20make%20italic%20until%20second%20last%20character%0A%0AUsing%20%60_%60%20as%20italic%20separator%20it%20does%20not%20work%3A%0A%0A**E_mp_**_ha_**_si_s**%0A%0AUsing%20%60*%60%20as%20italic%20separator%20it%20does%20not%20work%20either%3A%0A(ha)%20should%20not%20be%20bold%0A%0A**E*mp****ha****si*s**%0A%0AWhen%20strikethrough%20is%20used%20in%20place%20of%20italic%20it%20works%20as%20expected%0A%0A**E~~mp~~**~~ha~~**~~si~~s**)

**Expected behavior**

However if in place of italic strikethrough is used, everything works as expected.
It should bold first and last 3 characters. And then have italic from the second character to second last character.

**Comment by fredck** [comment]
Is the following case included in the issue? The formatting is not strictly mixed, just touching:

```
// Input
_te_**st**

// Expected output
<p><em>te</em><strong>st</strong></p>

// Actual output (wrong)
<p>_te_<strong>st</strong></p>
```

This was [working with v1.1.0](https://marked.js.org/demo/?outputType=html&text=_te_**st**&options=&version=1.1.0) and is [not working with v1.1.1](https://marked.js.org/demo/?outputType=html&text=_te_**st**&options=&version=1.1.1).

**Comment by calculuschild** [comment]
As far as the cases in the original post, keep these notes in mind:

1) Underscores can't be used for emphasis/strong inside of a word, because underscores are included in the set of "word characters" ( A-Z, a-z, 0-9, _ ) . That is, an underscore is just a normal `_` if between two alphanumeric characters, according to the [CommonMark spec](https://spec.commonmark.org/0.29/#can-open-emphasis).
2) Asterisks do not have this restriction. Also, because asterisks do not count as "word characters", you can have underscores adjacent to them and they should work properly.

That said, these are the correct outputs for each case (plus one more I added). Marked currently passes all of these except the all-asterisk one (case 4 below):

| Markdown | CommonMark Spec | Appearance |
|----|---|---|
| `**E_mp_**_ha_**_si_s**` | `<strong>E_mp_</strong><em>ha</em><strong>_si_s</strong>` | <strong>E_mp_</strong><em>ha</em><strong>_si_s</strong> |
| `__E*mp*__*ha*__*si*s__` | `<strong>E<em>mp</em></strong><em>ha</em><strong><em>si</em>s</strong>` | <strong>E<em>mp</em></strong><em>ha</em><strong><em>si</em>s</strong> |
| `**E*mp***_ha_***si*s**` | `<strong>E<em>mp</em></strong><em>ha</em><strong><em>si</em>s</strong>` | <strong>E<em>mp</em></strong><em>ha</em><strong><em>si</em>s</strong> |
| `**E*mp****ha****si*s**` | `<strong>E<em>mp</em><em><strong>ha</strong></em><em>si</em>s</strong>` | <strong>E<em>mp</em><em><strong>ha</strong></em><em>si</em>s</strong> |
| `__E_mp____ha____si_s__` | `<strong>E_mp____ha____si_s</strong>` | <strong>E_mp____ha____si_s</strong> |
