### ISSUE TITLE
Contents of inline HTML tag is being parsed as markdown

### ISSUE THREAD

**Issue by decademoon** [markedjs/marked#1376]
**Describe the bug**
If an inline HTML tag contains a newline, anything after the newline will be parsed as markdown.

**To Reproduce**
The following markdown source:

```
<section>
  Hello

  World
</section>
```

produces the following HTML:

```
<section>
  Hello

<p>  World</p>
</section>
```

but the expected HTML should be:

```
<section>
  Hello

  World
</section>
```

It works correctly in version 0.3.19 but not 0.5.1.

I can "fix" it by setting the pedantic option to true, but the docs mention that if pedantic is true then certain bugs won't be fixed (which bugs?), so I don't really want to set this. Is my markdown syntax incorrect?

**Comment by decademoon** [comment]
Ok this seems to be the way CommonMark works. Closing this because I don't think it's a marked bug.

**Comment by styfle** [comment]
You are correct, that CommonMark spec adds a the paragraph tag on a newline (it seems strange at first).

The goal of markdown was not to allow arbitrary html, it was meant to replace html and be readable as plain text.

> The overriding design goal for Markdown’s formatting syntax is to make it as readable as possible. The idea is that a Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions. While Markdown’s syntax has been influenced by several existing text-to-HTML filters, the single biggest source of inspiration for Markdown’s syntax is the format of plain text email. **[original source](https://daringfireball.net/projects/markdown/)**

When you use the `pedantic` flag, you are opting to use the original "buggy" implementation also known as `Markdown.pl`.

However, I suggest a solution to your problem is to add the literal HTML parts *after* you convert md to html.

For example, if I want to add a `<button>` to my markdown, I would do something like:

```js
var md = '# Some Website Content';
var html = marked(md) + '<h3>Stay up to date!</h3><button>Register</button>';
```
