### ISSUE TITLE
Tables are broken on v0.6

### ISSUE THREAD

**Issue by amejiarosario** [markedjs/marked#1429]
**Describe the bug**
[Tables](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables) are broken!

**To Reproduce**
Go to https://marked.js.org and use the following table with versions 0.3 and 0.4+

**Marked v0.3**
![image](https://user-images.githubusercontent.com/418605/53492170-31e9ec80-3a66-11e9-806a-773c9bd07326.png)

**Marked v0.4+**
![image](https://user-images.githubusercontent.com/418605/53492275-76758800-3a66-11e9-911a-88e3910faf7c.png)

Markdown example
```
Name | Insert | Access | Search | Delete | Comments
-|-|-|-|-
[**Array**](#Array) | [*O(n)*](#Insert-element-on-an-array) | [*O(1)*](#Access-an-element-in-an-array) | [*O(n)*](#Search-an-element-in-an-array) | [*O(n)*](#Deleting-elements-from-an-array) | Insertion to the end is `O(1)`. [Details here.](#Array-operations-time-complexity)
[(Hash)**Map**](#HashMaps) | [*O(1)**](#Insert-element-on-a-HashMap-runtime) | [*O(1)**](#Search-Access-an-element-on-a-HashMap-runtime) | [*O(1)**]
```

**Expected behavior**
The table should render as in versions 0.3

**Comment by UziTech** [comment]
Looks like you are missing a column for the line of dashes

```diff
- -|-|-|-|-
+ -|-|-|-|-|-
```

If you copy your markdown example into github it won't render as a table

**Comment by styfle** [comment]
Also compare [marked](https://marked.js.org/demo/?text=Name%20%7C%20Insert%20%7C%20Access%20%7C%20Search%20%7C%20Delete%20%7C%20Comments%0A-%7C-%7C-%7C-%7C-%0A%5B**Array**%5D(%23Array)%20%7C%20%5B*O(n)*%5D(%23Insert-element-on-an-array)%20%7C%20%5B*O(1)*%5D(%23Access-an-element-in-an-array)%20%7C%20%5B*O(n)*%5D(%23Search-an-element-in-an-array)%20%7C%20%5B*O(n)*%5D(%23Deleting-elements-from-an-array)%20%7C%20Insertion%20to%20the%20end%20is%20%60O(1)%60.%20%5BDetails%20here.%5D(%23Array-operations-time-complexity)%0A%5B(Hash)**Map**%5D(%23HashMaps)%20%7C%20%5B*O(1)**%5D(%23Insert-element-on-a-HashMap-runtime)%20%7C%20%5B*O(1)**%5D(%23Search-Access-an-element-on-a-HashMap-runtime)%20%7C%20%5B*O(1)**%5D&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) with the [commonmark](https://spec.commonmark.org/dingus/?text=Name%20%7C%20Insert%20%7C%20Access%20%7C%20Search%20%7C%20Delete%20%7C%20Comments%0A-%7C-%7C-%7C-%7C-%0A%5B**Array**%5D(%23Array)%20%7C%20%5B*O(n)*%5D(%23Insert-element-on-an-array)%20%7C%20%5B*O(1)*%5D(%23Access-an-element-in-an-array)%20%7C%20%5B*O(n)*%5D(%23Search-an-element-in-an-array)%20%7C%20%5B*O(n)*%5D(%23Deleting-elements-from-an-array)%20%7C%20Insertion%20to%20the%20end%20is%20%60O(1)%60.%20%5BDetails%20here.%5D(%23Array-operations-time-complexity)%0A%5B(Hash)**Map**%5D(%23HashMaps)%20%7C%20%5B*O(1)**%5D(%23Insert-element-on-a-HashMap-runtime)%20%7C%20%5B*O(1)**%5D(%23Search-Access-an-element-on-a-HashMap-runtime)%20%7C%20%5B*O(1)**%5D) output.

Neither produce a table.
This is probably due to better conformance to the commonmark spec.

**Comment by amejiarosario** [comment]
So it looks like version 0.3 was more forgiving. As @UziTech pointed out I was missing the `|-`.  Now, it works with any version of marked and github:

Name | Insert | Access | Search | Delete | Comments
-|-|-|-|-|-
[**Array**](#Array) | [*O(n)*](#Insert-element-on-an-array) | [*O(1)*](#Access-an-element-in-an-array) | [*O(n)*](#Search-an-element-in-an-array) | [*O(n)*](#Deleting-elements-from-an-array) | Insertion to the end is `O(1)`. [Details here.](#Array-operations-time-complexity)
[(Hash)**Map**](#HashMaps) | [*O(1)**](#Insert-element-on-a-HashMap-runtime) | [*O(1)**](#Search-Access-an-element-on-a-HashMap-runtime) | *O(1)*
