### ISSUE TITLE
inline html were parsed incorrectly

### ISSUE THREAD

**Issue by jinfagang** [markedjs/marked#1483]
Hi, I am just stucked in an issue. Previous I have my rendered markdown by markedjs it sometimes can not render in-line html right. I want it shows as html but render as pure text. 

Today I found that the problem is it render html inside p tag:

![image](https://user-images.githubusercontent.com/21303438/56947760-b5a48000-6b60-11e9-812b-7b429ee59884.png)

It just a markdown like this:

```

# Examples
Here are some results from our algorithm (from left to right are input, style and our output):

![](https://github.com/limingcv/Photorealistic-Style-Transfer/raw/master/supplementary_material/more_results/Comic/content.png)

![](https://github.com/limingcv/Photorealistic-Style-Transfer/raw/master/supplementary_material/more_results/Comic/style.png)

<img src="" width="31%" height="30%" align="center"/>
<img src="https://github.com/limingcv/Photorealistic-Style-Transfer/raw/master/supplementary_material/more_results/Comic/output.png" width="31%" height="30%" align="right"/>


<img src="https://github.com/limingcv/Photorealistic-Style-Transfer/raw/master/supplementary_material/more_results/Church/content.png" width="31%" height="30%" align="left"/>
<img src="https://github.com/limingcv/Photorealistic-Style-Transfer/raw/master/supplementary_material/more_results/Church/style.png" width="31%" height="30%" align="center"/>
<img src="https://github.com/limingcv/Photorealistic-Style-Transfer/raw/master/supplementary_material/more_results/Church/output.png" width="31%" height="30%" align="right"/>
```

What shoud I do to avoid it?

**Comment by jinfagang** [comment]
It just does not right:

![image](https://user-images.githubusercontent.com/21303438/56947878-074d0a80-6b61-11e9-9ab9-7138044f16bf.png)

**Comment by UziTech** [comment]
What version of marked are you using?

It looks like it is working fine in the latest version (v0.6.2) [demo](https://marked.js.org/demo/?text=%0A%23%20Examples%0AHere%20are%20some%20results%20from%20our%20algorithm%20(from%20left%20to%20right%20are%20input%2C%20style%20and%20our%20output)%3A%0A%0A!%5B%5D(https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FComic%2Fcontent.png)%0A%0A!%5B%5D(https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FComic%2Fstyle.png)%0A%0A%3Cimg%20src%3D%22%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22center%22%2F%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FComic%2Foutput.png%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22right%22%2F%3E%0A%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FChurch%2Fcontent.png%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22left%22%2F%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FChurch%2Fstyle.png%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22center%22%2F%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FChurch%2Foutput.png%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22right%22%2F%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.6.2)

**Comment by jinfagang** [comment]
@UziTech thanks for your reply, I am using 0.6.1

<img width="477" alt="image" src="https://user-images.githubusercontent.com/21303438/57008143-9a00ae80-6c20-11e9-99e1-7390ec8bae6c.png">

**Comment by UziTech** [comment]
it works in [v0.6.1](https://marked.js.org/demo/?text=%0A%23%20Examples%0AHere%20are%20some%20results%20from%20our%20algorithm%20(from%20left%20to%20right%20are%20input%2C%20style%20and%20our%20output)%3A%0A%0A!%5B%5D(https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FComic%2Fcontent.png)%0A%0A!%5B%5D(https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FComic%2Fstyle.png)%0A%0A%3Cimg%20src%3D%22%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22center%22%2F%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FComic%2Foutput.png%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22right%22%2F%3E%0A%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FChurch%2Fcontent.png%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22left%22%2F%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FChurch%2Fstyle.png%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22center%22%2F%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fgithub.com%2Flimingcv%2FPhotorealistic-Style-Transfer%2Fraw%2Fmaster%2Fsupplementary_material%2Fmore_results%2FChurch%2Foutput.png%22%20width%3D%2231%25%22%20height%3D%2230%25%22%20align%3D%22right%22%2F%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.6.1) as well. I'm thinking it is something else that is displaying it as a string instead of html.

Are you using a templating engine to display the marked output?

**Comment by jinfagang** [comment]
@UziTech  After using 0.6.2, it seems worked, but the formula inside html does not works very well, I am just convert it into html strings in js, then place a tag inside div tag. Maybe there is something strange problem
