### ISSUE TITLE
<br> in list element can cause inline markdown on next line to not be parsed

### ISSUE THREAD

**Issue by mjbvz** [markedjs/marked#1487]
**Describe the bug**
For the markdown:
```
- x
    <br>
    **bold**
```

`bold` is output as the literal string `**bold**` instead of as bold text. Current html output is:
```html
<ul>
<li>x  <br>
  **bold**
</li>
</ul>
```
**To Reproduce**

- [marked](https://marked.js.org/demo/?text=-%20x%0A%20%20%20%20%3Cbr%3E%0A%20%20%20%20**bold**%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

- [CommonMark](https://spec.commonmark.org/dingus/?text=-%20x%0A%20%20%20%20%3Cbr%3E%0A%20%20%20%20**bold**)

**Expected behavior**
The output should be:

```html
<ul>
<li>x
<br>
<strong>bold</strong></li>
</ul>
```

**Comment by UziTech** [comment]
looks like it works when `pedantic` is true.

[demo](https://marked.js.org/demo/?outputType=html&text=-%20x%0A%20%20%20%20%3Cbr%3E%0A%20%20%20%20**bold**%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20true%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by calculuschild** [comment]
This issue is not restricted to lists. It looks like the successive lines are just getting consumed into the HTML token in all cases.

https://marked.js.org/demo/?text=%3Cbr%3E%0A**bold**&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master

**Comment by UziTech** [comment]
Looks like this is actually working according to the spec [demo](https://spec.commonmark.org/dingus/?text=%3Cbr%3E%0A**bold**)

**Comment by UziTech** [comment]
raw html doesn't get parsed as markdown and after an opening html tag (like `<br>`) there must be a blank line before markdown parsing starts again.

**Comment by calculuschild** [comment]
In fact this is the spec for both opening *and* closing tags it looks like. I believe this would fit a "type 7" tag in the spec.

Relevant examples [193, 194, 195, 196](https://spec.commonmark.org/0.30/#example-163)
