### ISSUE TITLE
Modernizing the codebase

### ISSUE THREAD

**Issue by Andarist** [markedjs/marked#1539]
I'm wondering if you'd be interested in modernizing the codebase and introducing a build step. 

Why this could be beneficial? Currently marked in written solely in UMD format and this makes modern bundlers unable to even attempt at tree-shaking it. For example, I'd like to only use `Lexer` class and render things myself, but currently I end up with everything else what's exported by marked.

I, of course, offer my help to implement this - I would only make sure first if that's something you'd like to see happen.

**Note** I don't plan to introduce any breaking changes, the output files should still work in all currently supported environments etc.

**Comment by joshbruce** [comment]
Hello @Andarist.

We are currently working on ensuring compliance with currently supported standards; see the [milestones - 0.x specifically](https://github.com/markedjs/marked/milestones).

The 1.x and 2.x releases would be when something like this makes the most sense, I think.

If this is something you're passionate about, please do submit a PR on what that might look like in your mind. With that said, it may need to take second seat to security and markdown standard fixes.

**Comment by UziTech** [comment]
There are a couple PRs to update marked with a build step. #1349 #1452 

The problem with these PRs and updating marked to with a build step is that marked was originally created to be used in the browser and I believe we still have quite a few dependents using jsdelivr to include marked on the client side.

We would need a build step to create `/lib/marked.js` and `/marked.min.js` as a single file that would work with older browsers.

**Comment by Martii** [comment]
> ... I believe we still have quite a few dependents using jsdelivr to include marked on the client side.

If I'm reading and applying this right, I [brought up on another package](https://github.com/nfriedly/express-rate-limit/pull/152#issuecomment-509433428) *(and [they made an issue for it](https://github.com/nfriedly/express-rate-limit/pull/152#ref-issue-465856258))* we would prefer to have a static default build served alternately on GH in case npmjs.com is down depending on where we are at in development vs. production. Unforseen events can always happen with hosting. If npmjs.com were down we'd have to incorporate a build step in a hurry unless it was fully transparent with our static linking. We've already taken some precautions against npmjs.com outages but in a pickle there could be some events that could potentially take us down if our deps aren't available or if the main hosting maintainer is on break *(that would be me usually)*.

**Comment by UziTech** [comment]
Ideally we could offer an ES module output for anyone using a bundler on node and output  `/lib/marked.js` and `marked.min.js` with a build step as files on GitHub for anyone using a static build.

We currently have a build step to minify marked automatically on every successful push to master
https://github.com/markedjs/marked/blob/master/.travis.yml#L23

**Comment by Martii** [comment]
> ... a build step to minify marked automatically ...

Cool beans. Would be helpful to maintain the unminified too when this point comes for this issue *(and the others)* on the back-_(seat)_-burner. We currently use *express-minify* to minify cache everything we serve, including *marked* [here](https://github.com/OpenUserJS/OpenUserJS.org/blob/ff5980c936996e5bc939b8b39b80541797cae2c4/routesStatic.js#L86-L88), which in turn calls *terser* to do the actual one time minification so we don't end up doing it twice CPU wise. Obviously we can restrict *express-minify* from the *marked* path but prefer to keep all sources in the unadulterated state for debugging if needed. That other package I referenced is going to make it more time consuming to debug since we'll possibly get future errors in JavaScript but then it will need to be tracked down in TypeScript... kind of a bummer of the process of "modernizing" making issue reporting more complex.

**Comment by UziTech** [comment]
> kind of a bummer of the process with "modernizing" making issue reporting more complex.

I agree, we will try to keep `/lib/marked.js` unminified for easier debugging on older browsers.
