### ISSUE TITLE
[Complaint] Please do not try to use regex to parse such a complex language

### ISSUE THREAD

**Issue by qiujiangkun** [markedjs/marked#1549]
I know you are trying to use regex instead of other formal ways to do parsing jobs. Regex only works as a lexer, rather than a fully functional parser. 

Have you read any books on principles of compiling? If so, you will know why regex cannot work well when it comes to context-free grammar, which markdown needs.

PS: machine-generated parsers are way faster than regex-only "parsers", and handwritten ones are more extendable, by giving future programmers more space to modify in
 

```js
   var block = {
        newline: /^\n+/,
        code: /^( {4}[^\n]+\n*)+/,
        fences: noop,
        hr: /^ {0,3}((?:- *){3,}|(?:_ *){3,}|(?:\* *){3,})(?:\n+|$)/,
        heading: /^ *(#{1,6}) *([^\n]+?) *(?:#+ *)?(?:\n+|$)/,
        nptable: noop,
        blockquote: /^( {0,3}> ?(paragraph|[^\n]*)(?:\n|$))+/,
        list: /^( {0,3})(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,
        html: "^ {0,3}(?:<(script|pre|style)[\\s>][\\s\\S]*?(?:</\\1>[^\\n]*\\n+|$)|comment[^\\n]*(\\n+|$)|<\\?[\\s\\S]*?\\?>\\n*|<![A-Z][\\s\\S]*?>\\n*|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>\\n*|</?(tag)(?: +|\\n|/?>)[\\s\\S]*?(?:\\n{2,}|$)|<(?!script|pre|style)([a-z][\\w-]*)(?:attribute)*? */?>(?=\\h*\\n)[\\s\\S]*?(?:\\n{2,}|$)|</(?!script|pre|style)[a-z][\\w-]*\\s*>(?=\\h*\\n)[\\s\\S]*?(?:\\n{2,}|$))",
        def: /^ {0,3}\[(label)\]: *\n? *<?([^\s>]+)>?(?:(?: +\n? *| *\n *)(title))? *(?:\n+|$)/,
        table: noop,
        lheading: /^([^\n]+)\n *(=|-){2,} *(?:\n+|$)/,
        paragraph: /^([^\n]+(?:\n(?!hr|heading|lheading| {0,3}>|<\/?(?:tag)(?: +|\n|\/?>)|<(?:script|pre|style|!--))[^\n]+)*)/,
        text: /^[^\n]+/
    };
```

**Comment by joshbruce** [comment]
Noted. Thank you for the feedback. If you have any ideas that would help achieve this goal, please feel free to submit a PR. 

We aren't so much *trying* to use regex as much as we are *trying* to be compliant with the designated Markdown specifications before moving on to other things. The four members of the core team did not create Marked, we took it on for the large community of users.

There are also many other packages available now; so, if Marked is not fitting the bill for you due to its implementation, there are alternatives.

Again, thank you for the feedback.

Closing as this is a general statement of concern and not a defect or pure feature request.
