### ISSUE TITLE
Markdown strikethrough is not limited to two tilde wrapping

### ISSUE THREAD

**Issue by denizeren** [markedjs/marked#1561]
**Describe the bug**
According to [Github Flavored Markdown](https://github.github.com/gfm/#strikethrough-extension-) specification strikethrough text is any text wrapped in two tildes ( ~ ).  However marked library applies strikethrough to text when it's wrapped with single tildes ( ~ ) which causes unexpected behavior.

[GFM spec got updated](https://github.com/github/cmark-gfm/issues/99) for restricting strikethrough to two-tilde wrapping.

**To Reproduce**
1. Add any text between 2 tildes(ex: `~test~` ).
2. Paste it into [Marked Demo](https://marked.js.org/demo/?text=This%20should%20be%20strikethrough%3A%0A%0A~~strike%20it~~%0A%0AHowever%20these%20shouldn%27t%20be%20strikethrough%3A%0A%0A~don%27t%20strike%20it~%0A%0A~.%20also%20this%20.~%0A%0AHere%20tildes%20shouldn%27t%20show%20up%20since%20they%20are%20part%20of%20strikethrough%3A%0A%0A~~%20strike%20me%20~~&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) for viewing parsed HTML. You will see strikethrough text which shouldn't be strikethrough.

**Expected behavior**
Only two-tilde wrapped texts should be strikethrough.

See [example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22This%20should%20be%20strikethrough%3A%5Cn%5Cn~~strike%20it~~%5Cn%5CnHowever%20these%20shouldn%27t%20be%20strikethrough%3A%5Cn%5Cn~don%27t%20strike%20it~%5Cn%5Cn~.%20also%20this%20.~%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D).

**Comment by UziTech** [comment]
this is what `~test~` looks like on GitHub:
~test~

It looks like GitHub allows single tildes to be used for strikethrough even though the spec says otherwise.

**Comment by UziTech** [comment]
A little bit more research shows tests in GFM with single tildes as strikethrough.

https://github.com/github/cmark-gfm/blob/36c1553d2a1f04dc1628e76b18490edeff78b8d0/test/extensions.txt#L502-L510

It looks like this is a legacy issue. The spec was originally supposed to only support two tildes but, because of a long standing bug, a lot of strikethroughs on github.com are single tildes and GitHub [doesn't want to confuse it's users](https://github.com/github/cmark-gfm/issues/71#issuecomment-373170209).

Seems we have two options:

1. Change single tildes to do nothing and only allow strikethrough on double tilde.
2. Let single tildes be strikethrough like github.com

Since The GFM spec doesn't explicitly disallow single tildes from being used for strikethrough and the `gfm` option is supposed to copy what markdown looks like on github.com I say we leave it the way it is.

It looks like the reason for strikethrough to be two tildes is because single tildes are used by markdown-it as [subscript](https://github.com/markdown-it/markdown-it/issues/446), but until that is actually in a spec I don't see any reason we should change it.

**Comment by bladeSk** [comment]
For anyone who's looking for a quick fix:
`new marked.InlineLexer({ gfm: true }).rules.del = /^~~+(?=\S)([\s\S]*?\S)~~+/`

**Comment by zhao-chong** [comment]
> For anyone who's looking for a quick fix:
> `new marked.InlineLexer({ gfm: true }).rules.del = /^~~+(?=\S)([\s\S]*?\S)~~+/`

Thanks, but can you elaborate more on how to override this lexer rule to an existing marked instance? Thanks in advance.

**Comment by UziTech** [comment]
This is how you could use an extension to override the current behavior:

```js
const marked = require("marked");

marked.use({
  tokenizer: {
    del(src) {
      const cap = /^~~+(?=\S)([\s\S]*?\S)~~+/.exec(src);
      if (cap) {
        return {
          type: 'del',
          raw: cap[0],
          text: cap[2]
        };
      }
    }
  }
});
```

**Comment by UziTech** [comment]
The [spec](https://github.github.com/gfm/#strikethrough-extension-) now states that one or two tildes should work.
