### ISSUE TITLE
<pre> followed by empty line

### ISSUE THREAD

**Issue by andreasplesch** [markedjs/marked#1578]
**Describe the bug**
A pre tag html block is misrendered in the line following an initial empty line.

**To Reproduce**
1. [Marked Demo](https://marked.js.org/demo/?text=This%20does%20not%20work%20(leading%20tags%20and%20empty%20line)%3A%0A%3Cdiv%3E%3C%2Fdiv%3E%0A%3Cpre%3E%0A%0A%20%20%20%20%20%20%20%20G%20-%20H%20%20%20%20%20%20%20J%20-%20K%20-%20L%0A%20%20%20%20%20%20%20%2F%20%20%20%20%20%20%20%20%20%20%20%2F%0ACOM%20-%20B%20-%20C%20-%20D%20-%20E%20-%20F%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%5C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20I%0A%3C%2Fpre%3E%0A%0AThis%20works%20(no%20leading%20empty%20lines)%3A%0A%3Cdiv%3E%3C%2Fdiv%3E%0A%3Cpre%3E%0A%20%20%20%20%20%20%20%20G%20-%20H%20%20%20%20%20%20%20J%20-%20K%20-%20L%0A%20%20%20%20%20%20%20%2F%20%20%20%20%20%20%20%20%20%20%20%2F%0ACOM%20-%20B%20-%20C%20-%20D%20-%20E%20-%20F%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%5C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20I%0A%0A%3C%2Fpre%3E%0AThis%20also%20works%20(leading%20empty%20line%20but%20no%20initial%20white%20space)%3A%0A%3Cdiv%3E%3C%2Fdiv%3E%0A%3Cpre%3E%0A%0A%3D%20%20%20%20%20%20%20G%20-%20H%20%20%20%20%20%20%20J%20-%20K%20-%20L%0A%3D%20%20%20%20%20%20%2F%20%20%20%20%20%20%20%20%20%20%20%2F%0ACOM%20-%20B%20-%20C%20-%20D%20-%20E%20-%20F%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5C%5C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20I%0A%0A%3C%2Fpre%3E%0A%0ABackslashes%20%3F&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

2. [CommonMark Demo](https://spec.commonmark.org/dingus/) shows the same issue

The commonmark spec. explicitly treats pre tags as not being terminated by an empty line, to allow for proper rendering of white space. Both implementations seem non compliant.

**Expected behavior**
verbatim copying of text after pre tag as textcontent of a html pre element, until termination.

**Comment by UziTech** [comment]
It looks like the issue is that the `<div>` tag doesn't have a blank line after it. [demo](https://marked.js.org/demo/?text=%3Cdiv%3E%3C%2Fdiv%3E%0A%3Cpre%3E%0A%0A**a**%0A%3C%2Fpre%3E%0A%0A---%0A%0A%3Cdiv%3E%3C%2Fdiv%3E%0A%0A%3Cpre%3E%0A%0A**a**%0A%3C%2Fpre%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
The ending `</div>` is not considered the end of the html block but a blank line is.

According to the [spec](https://spec.commonmark.org/0.29/#example-118) the `<pre>` tag must have a blank line before it to act like a `<pre>` tag.

**Comment by UziTech** [comment]
![image](https://user-images.githubusercontent.com/97994/70369395-5a690780-187e-11ea-984e-16b778931114.png)

The yellow block is a markdown block and all other colors are HTML blocks.

**Comment by andreasplesch** [comment]
Let me look up  the language in the spec. but I do seem to recall that a closing tag suffices to terminate a div
