### ISSUE TITLE
v1.0.0 does not respect multiline code spans in list items

### ISSUE THREAD

**Issue by davidchambers** [markedjs/marked#1651]
v1.0.0:

```console
$ echo $'- `code\ncode`' | bin/marked
<ul>
<li>`code
code`</li>
</ul>
```

v0.8.2:

```console
$ echo $'- `code\ncode`' | bin/marked
<ul>
<li><code>code
code</code></li>
</ul>
```

This regression was introduced in 2806c4913c4e26b811f58eafbe73a17a9500d6d4.

**Comment by UziTech** [comment]
confirmed: [demo](https://marked.js.org/demo/?outputType=html&text=-%20%60code%0Acode%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

looks like the issue is the new line (`\n`) which should be turned into a space according to the spec.
