### ISSUE TITLE
require.js compatability

### ISSUE THREAD

**Issue by nayrangnu** [markedjs/marked#169]
marked only works with require.js if the wrapper `function` is commented out along with the caller as far as I can tell.

**Comment by poifox** [comment]
What if I don't want to save, say, blog posts as html but want to parse them in the template on render-time? 

For example, I was trying to use this lib with a Backbone app, and I'd like to have the marked() call in the template like this `<%= marked(body) %>` but I can't do that because marked won't be available to the templates.

Would I have to overload my model, and hence my server requests, with a parsed_body property?

**Comment by joshbruce** [comment]
For my generators, this wouldn't be a problem, but I don't know enough about marked to say.

@uzitech

**Comment by joshbruce** [comment]
Closing. Believe this has been fixed as of 0.3.19.
