### ISSUE TITLE
Links that end with single line break inadvertently includes the backslash character.

### ISSUE THREAD

**Issue by zxlin** [markedjs/marked#1758]
**Describe the bug**
Escaped new line (`'\\\n'`) for single line break gets grouped into URL links if the URL is at the end of the line.

**To Reproduce**
Compile to markdown the following plaintext
```
this is a url without a backslash: https://google.com\
this should be a new line
```
and observe this output:

this is a url without a backslash: https://google.com\
this should be a new line

--

You will find that the [Marked output](https://marked.js.org/demo/?text=this%20is%20a%20url%20without%20a%20backslash%3A%20https%3A%2F%2Fgoogle.com%5C%0Athis%20should%20be%20a%20new%20line&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master) is incorrect, but the [CommonMark output](https://spec.commonmark.org/dingus/?text=this%20is%20a%20url%20without%20a%20backslash%3A%20https%3A%2F%2Fgoogle.com%5C%0Athis%20should%20be%20a%20new%20line) is correct.

**Expected behavior**

it should show up as the following:

this is a url without a backslash: https://google.com \
this should be a new line

**Additional**
For what it's worth, Github's viewer has the same problem.

**Comment by UziTech** [comment]
This is because commonmark does not auto link urls like gfm.

According to the [GFM spec](https://github.github.com/gfm/#example-622)

> Trailing punctuation (specifically, `?`, `!`, `.`, `,`, `:`, `*`, `_`, and `~`) will not be considered part of the autolink

Which means any character not specified there will be considered part of the link.

You can fix this be including angle brackets around the link

```markdown
this is a url without a backslash: <https://google.com>\
this should be a new line
```
[demo](https://marked.js.org/demo/?text=this%20is%20a%20url%20without%20a%20backslash%3A%20%3Chttps%3A%2F%2Fgoogle.com%3E%5C%0Athis%20should%20be%20a%20new%20line&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
