### ISSUE TITLE
Broken sub-list indent with number prefix using version >= 1.2.3

### ISSUE THREAD

**Issue by jfcere** [markedjs/marked#1824]
**Marked version:**

\>= 1.2.3

**Describe the bug**

Starting with marked version 1.2.3, sub-list indentations are broken when used with number prefixes.

**To Reproduce**

Using the same markdown...

- Working example [using version 1.2.2](https://marked.js.org/demo/?text=%23%23%23%20With%20number%20prefix%0A%0A1.%20First%20ordered%20list%20item%0A2.%20Another%20item%0A%20%20*%20Unordered%20sub-list.%0A1.%20Actual%20numbers%20don%27t%20matter%2C%20just%20that%20it%27s%20a%20number%0A%20%201.%20Ordered%20sub-list%0A4.%20And%20another%20item.%0A%0A%23%23%23%20With%20dash%20prefix%0A%0A-%20First%20ordered%20list%20item%0A-%20Another%20item%0A%20%20-%20Unordered%20sub-list.%0A-%20Actual%20numbers%20don%27t%20matter%2C%20just%20that%20it%27s%20a%20number%0A%20%20-%20Ordered%20sub-list%0A-%20And%20another%20item.&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.2.2)

- Broken example [using version 1.2.3](https://marked.js.org/demo/?text=%23%23%23%20With%20number%20prefix%0A%0A1.%20First%20ordered%20list%20item%0A2.%20Another%20item%0A%20%20*%20Unordered%20sub-list.%0A1.%20Actual%20numbers%20don%27t%20matter%2C%20just%20that%20it%27s%20a%20number%0A%20%201.%20Ordered%20sub-list%0A4.%20And%20another%20item.%0A%0A%23%23%23%20With%20dash%20prefix%0A%0A-%20First%20ordered%20list%20item%0A-%20Another%20item%0A%20%20-%20Unordered%20sub-list.%0A-%20Actual%20numbers%20don%27t%20matter%2C%20just%20that%20it%27s%20a%20number%0A%20%20-%20Ordered%20sub-list%0A-%20And%20another%20item.&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=1.2.3)

**Expected behavior**

Expecting sub-list indentation with number prefix to be displayed as it was in version 1.2.2.

**Comment by UziTech** [comment]
That was fixed in v1.2.3 to match CommonMark [demo](https://spec.commonmark.org/dingus/?text=%23%23%23%20With%20number%20prefix%0A%0A1.%20First%20ordered%20list%20item%0A2.%20Another%20item%0A%20%20*%20Unordered%20sub-list.%0A1.%20Actual%20numbers%20don%27t%20matter%2C%20just%20that%20it%27s%20a%20number%0A%20%201.%20Ordered%20sub-list%0A4.%20And%20another%20item.%0A%0A%23%23%23%20With%20dash%20prefix%0A%0A-%20First%20ordered%20list%20item%0A-%20Another%20item%0A%20%20-%20Unordered%20sub-list.%0A-%20Actual%20numbers%20don%27t%20matter%2C%20just%20that%20it%27s%20a%20number%0A%20%20-%20Ordered%20sub-list%0A-%20And%20another%20item.)

The sub lists need to be indented to the level of the list content or they are considered a list item instead of a sub list.

It also matches github now.

## Github demo:

```markdown
### With number prefix

1. First ordered list item
2. Another item
  * Unordered sub-list.
1. Actual numbers don't matter, just that it's a number
  1. Ordered sub-list
4. And another item.

### With dash prefix

- First ordered list item
- Another item
  - Unordered sub-list.
- Actual numbers don't matter, just that it's a number
  - Ordered sub-list
- And another item.
```

### With number prefix

1. First ordered list item
2. Another item
  * Unordered sub-list.
1. Actual numbers don't matter, just that it's a number
  1. Ordered sub-list
4. And another item.

### With dash prefix

- First ordered list item
- Another item
  - Unordered sub-list.
- Actual numbers don't matter, just that it's a number
  - Ordered sub-list
- And another item.

**Comment by jfcere** [comment]
Alright, I wasn't sure it was intended and I had a test using sub-list that started failing after updating marked. 

Thanks, I'll close the issue.

**Comment by jfcere** [comment]
Looks like putting 3 leading spaces instead of 2 fixes the issue (in commonmark.js and GitHub)

```markdown
1. First ordered list item
2. Another item
   * Unordered sub-list.
1. Actual numbers don't matter, just that it's a number
   1. Ordered sub-list
4. And another item.
```

1. First ordered list item
2. Another item
   * Unordered sub-list.
1. Actual numbers don't matter, just that it's a number
   1. Ordered sub-list
4. And another item.
