### ISSUE TITLE
If there is space in between ** and **. The bold is not rendered correctly. 

### ISSUE THREAD

**Issue by lambda121** [markedjs/marked#1836]
**Marked version:**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by lambda121** [comment]
![Capture](https://user-images.githubusercontent.com/58508754/99611885-7ab3b700-2a3a-11eb-9a5c-00479fe5bddc.JPG)
I am using react-draft-wysiwyg.

"**Preview** Screen" works correctly
but not "**Preview **Screen"

**Comment by calculuschild** [comment]
The extra spaces immediately before or after the asterisks in `**Preview **` are invalid markdown and should be rendered as asterisks instead of `<strong>`.  Earlier versions of Marked.js incorrectly allowed this behavior, but this has since been fixed to more accurately follow the [Markdown spec](https://github.github.com/gfm/#example-361) .

So this is actually correct behavior.
