### ISSUE TITLE
How to change or disable checkbox token/render?

### ISSUE THREAD

**Issue by Aparus** [markedjs/marked#1915]
Hi. Thank you for great parser! Can I ask help? I can't find answer in docs...

1) I need to improve checkbox parsing, for it get any non-space symbol as "checked". By default checked is only [x] and [X] how I know. But in some languages it is hard to write this symbols (switch keyboards, etc). 

```
- [x] first variant 
- [ ] second variant 
- [v] third variant 
```

Then I use in renderer: `checkbox => checked? <checkbox correct /> : <checkbox /> `
(that I know how to do, but for now `checked` argument is wrong, if I use not [xX]). 

2) I need to add other content similar to checkbox... radiobutton:
```
- ( ) first variant 
- ( ) second variant 
- (v) third variant 
```
Finally I need this kind of output:
```
<ul>
<li><checkbox correct /> first variant </li>
<li><checkbox /> second variant </li>
<li><checkbox correct />third variant </li>
</ul>
```
```
<ul>
<li><radiobutton /> first variant </li>
<li><radiobutton /> second variant </li>
<li><radiobutton correct />third variant </li>
</ul>
```
If there is no way to do that, how to disable ckeckbox rendering? Just for it be `<li> [ ] variant first </li>` ? 

I'm using marked v1.2.0

**Comment by UziTech** [comment]
[Task lists](https://github.github.com/gfm/#task-list-items-extension-) are part of GFM spec. you can turn gfm off by using the option: `gfm: false`.

If you still need `gfm` but just don't want task lists you will have to override the `checkbox` [renderer](https://marked.js.org/using_pro#renderer).

```js
const marked = require('marked');

const renderer = {
  checkbox(checked) {
    // don't render checkbox
    return '';
  }
};

marked.use({ renderer });

console.log(marked(markdown));
```

If you want to render checkbox by using a character other than `x` or `X` than you will have to override the `list` tokenizer. That is quite a task since you will have to copy most of the current [list tokenizer](https://github.com/markedjs/marked/blob/master/src/Tokenizer.js#L205-L315)

**Comment by Aparus** [comment]
@UziTech thank you. So detailed answer!
