### ISSUE TITLE
Shouldn't be space after a list (in lexer)? 

### ISSUE THREAD

**Issue by ApayRus** [markedjs/marked#1954]
In version 2.0.1 marked team closed my issue #1947 about space in the last list item in lexer. Thank you, I was happy to receive email about it. 

Now space after list doesn't exist at all. Space appears after header, paragraph, blockquote... But space doesn't appear after list. I think it should be there. 

Here is [a sandbox with some code](https://codesandbox.io/s/marked-lexer-to-react-components-6enjk?file=/src/App.js). You can see in console `lexerOutput` and visualize what I am talking about.

**Comment by UziTech** [comment]
It looks like the space token after the header is because of the spaces in the blank line.

[demo without spaces](https://marked.js.org/demo/?outputType=lexer&text=%23%20header%20%0A%0Aparagraph%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
[demo with spaces](https://marked.js.org/demo/?outputType=lexer&text=%23%20header%20%0A%20%20%0Aparagraph%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

I agree the tokens should be more consistent.

**Comment by Aparus** [comment]
> It looks like the space token after the header is because of the spaces in the blank line.
After list space doesn't appear even when you put there a blank line.

**Comment by UziTech** [comment]
It does if there are space characters in the blank line after the list.

[demo](https://marked.js.org/demo/?outputType=lexer&text=%23%20header%20%0A%20%20%0Aparagraph%0A%0A-%20one%0A-%20two%0A%20%20%0AParagraph&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by Aparus** [comment]
Yes, I see. But... h
- header don't kill blank line after it, 
- blockquote don't kill blank line after it, 
- paragraph don't kill blank line after it 

--- all these elements keep blank lines after them and you see it in lexer and can visualize. 
Why list should kill blank line after it? 
Why should I add 2 blank lines after list, when I always add 1 blank line after everything in this markdown universe? :-D

**Comment by UziTech** [comment]
As I said above, I agree they should be more consistent. We always appreciate PRs 😁👍

**Comment by UziTech** [comment]
Just curious what you use the tokens for? It seems like you should be able to just skip the space tokens since they don't affect rendering.

**Comment by Aparus** [comment]
> Just curious what you use the tokens for? It seems like you should be able to just skip the space tokens since they don't affect rendering.

I render tokens into react-native elements like <View> and <Text> with different styles. And I want to make one space style, like `<View style={styles.space} /> ` with fixed size. Otherwise I should add margin for any elements. It is not so hard. But annoying, how you labeled this issue )

**Comment by UziTech** [comment]
L2-annoying just mean it is a low priority bug.
