### ISSUE TITLE
Option to turn a lexed Token Tree back into markdown

### ISSUE THREAD

**Issue by donmahallem** [markedjs/marked#1986]
**Describe the feature**
Currently one is able to tokenize Markdown but not able to turn it back into markdown

**Why is this feature necessary?**
As turning markdown into html is pretty useful for readme generation an option to read a markdown file, manipulate the Token Tree and turn it back into markdown is a nice option in my opinion

**Describe alternatives you've considered**
I tried to write my own renderer but hit limitations on how marked expects the data to be rendered. For example ListItems can't be turned back into a Markdown list

**Comment by calculuschild** [comment]
Could you clarify why you want Markdown as output, rather than HTML? It sounds like in the end, you still want HTML as the output (for readme generation).

There are many ways to extend/modify the output of Marked.js beyond just using a custom renderer if the renderer alone isn't working for you, but going from `Markdown -> Tokens -> Markdown again -> back to Tokens -> HTML` seems like an extra set of steps that aren't needed. If you give us a specific use case, perhaps with example input and output code that would help explain what you need.

**Comment by UziTech** [comment]
You should be able to use the `raw` property of the tokens to do this.

Something like:

```js
const tokens = marked.lexer(markdown);
const html = tokens.reduce((s, t) => s + t.raw, '');
```

**Comment by UziTech** [comment]
I agree with @calculuschild though. Marked is focused on creating HTML from markdown. If you want to get markdown from HTML you can use [turndown](https://github.com/domchristie/turndown).

**Comment by donmahallem** [comment]
What I want as final output is just markdown not html(eg. README.md on GitHub). This shouldn't interfere with the goal of being a fast markdown to html converter. Just an optional feature.

I do have a use case for this and did write my own dirty token list to markdown converter but it is yet not mature. I could contribute it if there is interest otherwise I would publish it as my own package.

Just wanted to hear if there is any interest to incorporate this.

**Comment by UziTech** [comment]
That should be a separate package.

Your best bet would be to do something like:

Tokenize markdown -> Manipulate Tokens -> Render tokens to html -> Run html through turndown -> Get optimized markdown.

**Comment by pvamshi** [comment]
@donmahallem 
I am interested in markdown renderer. Can you share your code
