### ISSUE TITLE
HTML inside markdown will cause it fail to parse.

### ISSUE THREAD

**Issue by Nness** [markedjs/marked#2018]
**Marked version:**: Since `1.2.2`, latest I have test is `2.0.2`. 

**Describe the bug**
In version `1.2.2` to `2.0.2`, all those version have issue where if there is HTML inside markdown, it will cause anything after HTML to not be parsed.

**To Reproduce**

```
 ### Title

<h3>Header 3</h3>

<p style="font-size:14px;">First HTML sentence</p>

<p style="font-size:14px;">Second HTML sentence</p>

<p style="font-size:14px;">Third HTML sentence</p>  

  

### Full Name

Test name

  
### ABC title with space at end of line  
Another line
```

**marked options**
```
    const options: MarkedOptions = {
      smartypants: true,
      gfm: true,
      breaks: true,
      silent: true
    };
```

**Expected behavior**
Markdown after HTML should be parsed. This was fine on version `1.1.1`.

**Comment by UziTech** [comment]
It looks like it is working fine in this [demo](https://marked.js.org/demo/?text=%20%23%23%23%20Title%0A%0A%3Ch3%3EHeader%203%3C%2Fh3%3E%0A%0A%3Cp%20style%3D%22font-size%3A14px%3B%22%3EFirst%20HTML%20sentence%3C%2Fp%3E%0A%0A%3Cp%20style%3D%22font-size%3A14px%3B%22%3ESecond%20HTML%20sentence%3C%2Fp%3E%0A%0A%3Cp%20style%3D%22font-size%3A14px%3B%22%3EThird%20HTML%20sentence%3C%2Fp%3E%20%20%0A%0A%20%20%0A%0A%23%23%23%20Full%20Name%0A%0ATest%20name%0A%0A%20%20%0A%23%23%23%20ABC%20title%20with%20space%20at%20end%20of%20line%20%20%0AAnother%20line&options=%7B%0A%20%20%22smartypants%22%3A%20true%2C%0A%20%20%22gfm%22%3A%20true%2C%0A%20%20%22breaks%22%3A%20true%2C%0A%20%20%22silent%22%3A%20true%0A%7D&version=master). Even if you change the version to 2.0.2.

Could you explain more about where this is happening and your exact code?

**Comment by Nness** [comment]
@UziTech I have tried to reproduce on online editor such as codepen, but fail to do so. I have now successfully created an demo with Angular 2 repository. Which you can access at [here](https://github.com/Nness/marked-issue). 

Once cloned, execute `npm install`, then `npm start`. You should be able to see a section of parsed markdown at `http://localhost:4200/`. 

The marked version I have used is 2.0.3. I do use custom renderer, but even without the custom renderer, the problem still persist I believe.

**Comment by UziTech** [comment]
I see the issue. Your markdown is indented ([demo](https://marked.js.org/demo/?text=%20%23%23%23%20Title%0A%0A%20%20%3Ch3%3EHeader%203%3C%2Fh3%3E%0A%20%20%0A%20%20%3Cp%20style%3D%22font-size%3A14px%3B%22%3EFirst%20HTML%20sentence%3C%2Fp%3E%0A%20%20%0A%20%20%3Cp%20style%3D%22font-size%3A14px%3B%22%3ESecond%20HTML%20sentence%3C%2Fp%3E%0A%20%20%0A%20%20%3Cp%20style%3D%22font-size%3A14px%3B%22%3EThird%20HTML%20sentence%3C%2Fp%3E%20%20%0A%20%20%0A%20%20%20%20%0A%20%20%0A%20%20%23%23%23%20Full%20Name%0A%20%20%0A%20%20Test%20name%0A%20%20%0A%20%20%20%20%0A%20%20%23%23%23%20ABC%20title%20with%20space%20at%20end%20of%20line%20%20%0A%20%20Another%20line&options=%7B%0A%20%20%22smartypants%22%3A%20true%2C%0A%20%20%22gfm%22%3A%20true%2C%0A%20%20%22breaks%22%3A%20true%2C%0A%20%20%22silent%22%3A%20true%0A%7D&version=master)).

The html elements are ended at the first blank line but you don't have any actual blank lines after the html elements because they all have space characters in them.

Marked should be fixed to see lines with only spaces as blank lines but you can also fix it by removing the spaces from blank lines.

**Comment by Nness** [comment]
Looks like that is cause, we will use older version until its fixed. Thanks

**Comment by UziTech** [comment]
If you want to create a PR it could be fixed faster 😁👍

**Comment by krassowski** [comment]
After checking different versions with the interactive demo tool I believe that it was introduced in 1.2.8, so thins might have been related to this PR: https://github.com/markedjs/marked/pull/1889

**Comment by krassowski** [comment]
Should the following render markdown as well (no new lines) too?

```
<details>
   <summary>Dropdown title</summary>
   ## Hidden text.
</details>
```

(Currently it [doesn't](https://marked.js.org/demo/?text=%3Cdetails%3E%0A%20%20%20%3Csummary%3EDropdown%20title%3C%2Fsummary%3E%0A%20%20%20%23%23%20Hidden%20text.%0A%3C%2Fdetails%3E&options=%7B%0A%20%20%22smartypants%22%3A%20true%2C%0A%20%20%22gfm%22%3A%20true%2C%0A%20%20%22breaks%22%3A%20true%2C%0A%20%20%22silent%22%3A%20true%0A%7D&version=master))

**Comment by UziTech** [comment]
@krassowski no according to the [spec](https://spec.commonmark.org/0.29/#html-blocks)

**Comment by krassowski** [comment]
Indeed. It might not be a great UX but I guess this how the spec was defined, so no discussion here. Does it mean that my #2052 PR does solve this issue properly?
