### ISSUE TITLE
Inconsistent token type for raw emails

### ISSUE THREAD

**Issue by katafractari** [markedjs/marked#2072]
**Marked version: 2.0.5**

**Describe the bug**
Only first raw email in markdown is treated as token type *link*, all other are treated as *text*.

**To Reproduce** 
1. Only one email in the markdown - treated as a token of type **link**: https://replit.com/@katafractari/CompassionateOurSandboxes
2. URL and an email in the markdown, email is treated as token of type **text**: https://replit.com/@katafractari/CompassionateOurSandboxes-1

**Expected behavior**
All emails should be treated as the same type of token.

Also in marked demo, the first email is treated as text type: https://marked.js.org/demo/?outputType=lexer&text=info%40email.io&options=&version=2.0.5

**Comment by UziTech** [comment]
In your demo you have `gfm` turned off which is why it doesn't show a link. [demo with gfm on](https://marked.js.org/demo/?outputType=lexer&text=info%40email.io&options=%7B%22gfm%22%3A%20true%7D&version=2.0.5)

It looks like the behavior in the second link is a bug. If you add a second space after the url then it renders correctly. [demo](https://marked.js.org/demo/?text=https%3A%2F%2Fmarked.js.org%20%20info%40email.io&options=%7B%22gfm%22%3A%20true%7D&version=2.0.5)

**Comment by katafractari** [comment]
Thanks for the fix.
