### ISSUE TITLE
Uncaught InternalError: too much recursion

### ISSUE THREAD

**Issue by davidak** [markedjs/marked#2074]
**Marked version:**

**Describe the bug**

```
Uncaught InternalError: too much recursion
Please report this to https://github.com/markedjs/marked.
    strong https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    inlineTokens https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    inline https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    lex https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    lex https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    ge https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    za https://www.protondb.com/static/js/main.f70ca061.chunk.js:1
    oa https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    qs https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Ou https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Tu https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Au https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    yu https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Wo https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    unstable_runWithPriority https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Ho https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Wo https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Vo https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Cu https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    unstable_runWithPriority https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Ho https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    _u https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    Su https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    P https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    onmessage https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    EventHandlerNonNull* https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    r https://www.protondb.com/app/271590:1
    <anonymous> https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    r https://www.protondb.com/app/271590:1
    <anonymous> https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    r https://www.protondb.com/app/271590:1
    <anonymous> https://www.protondb.com/static/js/661.b1c624e9.chunk.js:2
    r https://www.protondb.com/app/271590:1
    521 https://www.protondb.com/static/js/main.f70ca061.chunk.js:1
    r https://www.protondb.com/app/271590:1
    b https://www.protondb.com/app/271590:1
    a https://www.protondb.com/app/271590:1
    <anonymous> https://www.protondb.com/static/js/main.f70ca061.chunk.js:1
```

**To Reproduce**

1. open https://www.protondb.com/app/271590
2. open console
3. sort distro: nixos
4. the page crashes, get error from above

**Expected behavior**
no error

**Comment by UziTech** [comment]
Can you give us the markdown or try to create the error in a [demo](https://marked.js.org/demo/)?

**Comment by davidak** [comment]
No, i'm just a user of that website and don't have the code.

@bdefore is the only one who has the code and could provide more details.

**Comment by UziTech** [comment]
We would need to know what markdown is causing it, what version of marked is being used, and what options are used to be able to debug it.

**Comment by bdefore** [comment]
@davidak i can reproduce a problem with the page not loading once the sort distro is set. i don't expect that this is a problem with the marked library, but rather that there's too much data asked to be parsed for that game or there's a submission with some pattern that's causing the recursion. unfortunately on my side with chrome i just get an unresponsive page rather than the script error you do. i'll need a bit more time to look into this.

**Comment by UziTech** [comment]
@bdefore Based on the stack trace it looks like protondb is using marked v1 which does have some vulnerabilities in the `strong` tokenizer. v2 fixed these vulnerabilities by combining `em` and `strong` tokenizers. This might be fixed by updating marked. I could help with that if there are custom renderers being used.

**Comment by bdefore** [comment]
@UziTech indeed i was on v1 and an update to 2.0.6 does appear fix the issue (although it takes a while to render the page). it's unclear to me if this is due to v2 changes for better performance or a bug fix in parsing. if you'd like to diagnose further for a potential v1 fix, the data i'm trying to render from the marked library is all of the child nodes within `responses` -> `notes` for each entry in this array: https://gist.githubusercontent.com/bdefore/3bc8f8936e4a8c5fa744bfa3d90e4919/raw/ba2f6337d5f4ba6473010130a104a6daff0353b0/test.json

**Comment by UziTech** [comment]
Looks like the offending markdown was a line of underscores which is known to be vulnerable in v1 (see #1927).

I would recommend running dompurify on the output of marked instead of the input since it could be easy for someone to output a malicious link or possibly other markdown.

```js
dompurify.sanitize(marked(str, { smartypants: true }))
```
