### ISSUE TITLE
Relative paths get resolved incorrectly to invalid format

### ISSUE THREAD

**Issue by VasuBhog** [markedjs/marked#2135]
**Marked version:** 1.1.0

**Describe the bug**

We utilize marked js to parse the markdown that is entered by the user. 

We are passing in a relative path to marked.parse function and find that the returned html is removing the initial parent directory slash ('\') and concatenating the ..'s (periods).

ex. **'..\..\test.ipynb'** gets converted to \<p\>**....\test.ipynb\</p\>**

**To Reproduce**

Using marked 1.1.0, and testing a relative path shown below via the markdown.parse function will output the relative path in an invalid format. 
```
console.log(marked.parse('..\\..\\test.ipynb'))
returns '<p>....\test.ipynb</p>'
```

This in turn would resolve our link that the user inputs to fail upon opening since the path does is not formatted correctly.

**Expected behavior**

marked.parse should return the relative path in the same format of parent directories shown below: 
```
console.log(marked.parse('..\\..\\test.ipynb'))
returns '<p>..\..\test.ipynb</p>'
```

**Comment by UziTech** [comment]
Are you able to reproduce this in a [demo](https://marked.js.org/demo/?outputType=html&text=..%5C%5C..%5C%5Ctest.ipynb&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)?

Also v1.1.0 is very old latest version is v2.1.3

**Comment by UziTech** [comment]
I see the issue in [this demo](https://marked.js.org/demo/?outputType=lexer&text=..%5C..%5Ctest.ipynb&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=2.1.3)

This actually matches [CommonMark](https://spec.commonmark.org/dingus/?text=..%5C..%5Ctest.ipynb) because `\.` in markdown is an escaped `.` according to the [spec](https://spec.commonmark.org/0.30/#backslash-escapes)
