### ISSUE TITLE
Reference-style links inside tables are broken since version 3

### ISSUE THREAD

**Issue by elishowk** [markedjs/marked#2217]
**Marked version: 3+**

**Describe the bug**

Reference-style links inside tables are broken since version 3. Version 2.1.3 works fine.

`[I'm a reference-style link][Arbitrary case-insensitive reference text]`

**To Reproduce**

- [Breaking example with v3](https://marked.js.org/demo/?text=%7C%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20H%3D128%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20H%3D256%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20H%3D512%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20H%3D768%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20--------%20%7C%20%3A-----------------------%3A%20%7C%20%3A-----------------------%3A%20%7C%20%3A-------------------------%3A%20%7C%20%3A-------------------------%3A%7C%0A%7C%20**L%3D2**%20%20%7C%20%5B**2%2F128%20(Tiny)**%5D%5B2_128%5D%20%7C%20%20%20%20%20%20%5B2%2F256%5D%5B2_256%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B2%2F512%5D%5B2_512%5D%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B2%2F768%5D%5B2_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D4**%20%20%7C%20%20%20%20%20%20%5B4%2F128%5D%5B4_128%5D%20%20%20%20%20%20%20%7C%20%5B**4%2F256%20(Mini)**%5D%5B4_256%5D%20%7C%20%5B**4%2F512%20(Small)**%5D%5B4_512%5D%20%20%7C%20%20%20%20%20%20%20%5B4%2F768%5D%5B4_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D6**%20%20%7C%20%20%20%20%20%20%5B6%2F128%5D%5B6_128%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B6%2F256%5D%5B6_256%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B6%2F512%5D%5B6_512%5D%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B6%2F768%5D%5B6_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D8**%20%20%7C%20%20%20%20%20%20%5B8%2F128%5D%5B8_128%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B8%2F256%5D%5B8_256%5D%20%20%20%20%20%20%20%7C%20%5B**8%2F512%20(Medium)**%5D%5B8_512%5D%20%7C%20%20%20%20%20%20%20%5B8%2F768%5D%5B8_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D10**%20%7C%20%20%20%20%20%5B10%2F128%5D%5B10_128%5D%20%20%20%20%20%20%7C%20%20%20%20%20%5B10%2F256%5D%5B10_256%5D%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B10%2F512%5D%5B10_512%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B10%2F768%5D%5B10_768%5D%20%20%20%20%20%20%7C%0A%7C%20**L%3D12**%20%7C%20%20%20%20%20%5B12%2F128%5D%5B12_128%5D%20%20%20%20%20%20%7C%20%20%20%20%20%5B12%2F256%5D%5B12_256%5D%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B12%2F512%5D%5B12_512%5D%20%20%20%20%20%20%20%7C%20%5B**12%2F768%20(Base)**%5D%5B12_768%5D%7C%0A%0A%5B2_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-128%0A%5B2_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-256%0A%5B2_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-512%0A%5B2_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-768%0A%5B4_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-128%0A%5B4_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-256%0A%5B4_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-512%0A%5B4_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-768%0A%5B6_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-128%0A%5B6_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-256%0A%5B6_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-512%0A%5B6_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-768%0A%5B8_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-128%0A%5B8_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-256%0A%5B8_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-512%0A%5B8_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-768%0A%5B10_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-128%0A%5B10_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-256%0A%5B10_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-512%0A%5B10_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-768%0A%5B12_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-128%0A%5B12_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-256%0A%5B12_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-512%0A%5B12_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-768&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=3.0.4)

1. Install marked `npm install --save marked@3.0.4` 

**Expected behavior**

- [Working format with v2.1.3](https://marked.js.org/demo/?text=%7C%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20H%3D128%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20H%3D256%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20H%3D512%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20H%3D768%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20--------%20%7C%20%3A-----------------------%3A%20%7C%20%3A-----------------------%3A%20%7C%20%3A-------------------------%3A%20%7C%20%3A-------------------------%3A%7C%0A%7C%20**L%3D2**%20%20%7C%20%5B**2%2F128%20(Tiny)**%5D%5B2_128%5D%20%7C%20%20%20%20%20%20%5B2%2F256%5D%5B2_256%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B2%2F512%5D%5B2_512%5D%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B2%2F768%5D%5B2_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D4**%20%20%7C%20%20%20%20%20%20%5B4%2F128%5D%5B4_128%5D%20%20%20%20%20%20%20%7C%20%5B**4%2F256%20(Mini)**%5D%5B4_256%5D%20%7C%20%5B**4%2F512%20(Small)**%5D%5B4_512%5D%20%20%7C%20%20%20%20%20%20%20%5B4%2F768%5D%5B4_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D6**%20%20%7C%20%20%20%20%20%20%5B6%2F128%5D%5B6_128%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B6%2F256%5D%5B6_256%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B6%2F512%5D%5B6_512%5D%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B6%2F768%5D%5B6_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D8**%20%20%7C%20%20%20%20%20%20%5B8%2F128%5D%5B8_128%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B8%2F256%5D%5B8_256%5D%20%20%20%20%20%20%20%7C%20%5B**8%2F512%20(Medium)**%5D%5B8_512%5D%20%7C%20%20%20%20%20%20%20%5B8%2F768%5D%5B8_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D10**%20%7C%20%20%20%20%20%5B10%2F128%5D%5B10_128%5D%20%20%20%20%20%20%7C%20%20%20%20%20%5B10%2F256%5D%5B10_256%5D%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B10%2F512%5D%5B10_512%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B10%2F768%5D%5B10_768%5D%20%20%20%20%20%20%7C%0A%7C%20**L%3D12**%20%7C%20%20%20%20%20%5B12%2F128%5D%5B12_128%5D%20%20%20%20%20%20%7C%20%20%20%20%20%5B12%2F256%5D%5B12_256%5D%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B12%2F512%5D%5B12_512%5D%20%20%20%20%20%20%20%7C%20%5B**12%2F768%20(Base)**%5D%5B12_768%5D%7C%0A%0A%5B2_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-128%0A%5B2_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-256%0A%5B2_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-512%0A%5B2_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-768%0A%5B4_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-128%0A%5B4_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-256%0A%5B4_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-512%0A%5B4_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-768%0A%5B6_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-128%0A%5B6_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-256%0A%5B6_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-512%0A%5B6_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-768%0A%5B8_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-128%0A%5B8_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-256%0A%5B8_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-512%0A%5B8_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-768%0A%5B10_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-128%0A%5B10_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-256%0A%5B10_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-512%0A%5B10_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-768%0A%5B12_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-128%0A%5B12_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-256%0A%5B12_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-512%0A%5B12_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-768&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=2.1.3)

**Comment by tHeCh0s3n0n3** [comment]
I ran into this very issue and did a bit of troubleshooting (I'm using a custom renderer).

What I found was that the tablecell render function receives a rendered link as the content in the following cases which is the expected behavior:
* When the link is fully formed (i.e. `[test](url)`)
* When the link's reference is declared *above* the table cell ([working example based on elishowk's](https://marked.js.org/demo/?text=%5B2_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-128%0A%5B2_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-256%0A%5B2_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-512%0A%5B2_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-2_H-768%0A%5B4_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-128%0A%5B4_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-256%0A%5B4_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-512%0A%5B4_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-4_H-768%0A%5B6_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-128%0A%5B6_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-256%0A%5B6_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-512%0A%5B6_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-6_H-768%0A%5B8_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-128%0A%5B8_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-256%0A%5B8_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-512%0A%5B8_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-8_H-768%0A%5B10_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-128%0A%5B10_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-256%0A%5B10_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-512%0A%5B10_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-10_H-768%0A%5B12_128%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-128%0A%5B12_256%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-256%0A%5B12_512%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-512%0A%5B12_768%5D%3Ahttps%3A%2F%2Fhuggingface.co%2Fuer%2Fchinese_roberta_L-12_H-768%0A%0A%7C%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20H%3D128%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20H%3D256%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20H%3D512%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%20%20%20%20%20H%3D768%20%20%20%20%20%20%20%20%20%20%20%7C%0A%7C%20--------%20%7C%20%3A-----------------------%3A%20%7C%20%3A-----------------------%3A%20%7C%20%3A-------------------------%3A%20%7C%20%3A-------------------------%3A%7C%0A%7C%20**L%3D2**%20%20%7C%20%5B**2%2F128%20(Tiny)**%5D%5B2_128%5D%20%7C%20%20%20%20%20%20%5B2%2F256%5D%5B2_256%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B2%2F512%5D%5B2_512%5D%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B2%2F768%5D%5B2_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D4**%20%20%7C%20%20%20%20%20%20%5B4%2F128%5D%5B4_128%5D%20%20%20%20%20%20%20%7C%20%5B**4%2F256%20(Mini)**%5D%5B4_256%5D%20%7C%20%5B**4%2F512%20(Small)**%5D%5B4_512%5D%20%20%7C%20%20%20%20%20%20%20%5B4%2F768%5D%5B4_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D6**%20%20%7C%20%20%20%20%20%20%5B6%2F128%5D%5B6_128%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B6%2F256%5D%5B6_256%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B6%2F512%5D%5B6_512%5D%20%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%20%5B6%2F768%5D%5B6_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D8**%20%20%7C%20%20%20%20%20%20%5B8%2F128%5D%5B8_128%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B8%2F256%5D%5B8_256%5D%20%20%20%20%20%20%20%7C%20%5B**8%2F512%20(Medium)**%5D%5B8_512%5D%20%7C%20%20%20%20%20%20%20%5B8%2F768%5D%5B8_768%5D%20%20%20%20%20%20%20%7C%0A%7C%20**L%3D10**%20%7C%20%20%20%20%20%5B10%2F128%5D%5B10_128%5D%20%20%20%20%20%20%7C%20%20%20%20%20%5B10%2F256%5D%5B10_256%5D%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B10%2F512%5D%5B10_512%5D%20%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B10%2F768%5D%5B10_768%5D%20%20%20%20%20%20%7C%0A%7C%20**L%3D12**%20%7C%20%20%20%20%20%5B12%2F128%5D%5B12_128%5D%20%20%20%20%20%20%7C%20%20%20%20%20%5B12%2F256%5D%5B12_256%5D%20%20%20%20%20%20%7C%20%20%20%20%20%20%5B12%2F512%5D%5B12_512%5D%20%20%20%20%20%20%20%7C%20%5B**12%2F768%20(Base)**%5D%5B12_768%5D%7C%0A%0A&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=3.0.4))

The bug only appears when the link reference is declared *below* where it is referenced.

The simplest workaround would be to move your link reference declarations to the top of the markdown file.

**Comment by Martii** [comment]
@tHeCh0s3n0n3

> The bug only appears when the link reference is declared below where it is referenced.

> The simplest workaround would be to move your link reference declarations to the top of the markdown file.

Interesting... doesn't appear to be needed exactly at the top of the .md file though as you alluded to... just above the references. This is what has been stopping us from migrating to a newer *marked*.

Not sure I want to ask all of our users to do this though... not to mention any comments to be fixed. OY.

Thanks for the workaround mention.

**Comment by ashharrison90** [comment]
also seeing this.

wrote an ugly little test case:
```javascript
it('should correctly parse reference links in tables', () => {
  const md = `
| Column 1 | Column 2             |
|----------|--------------------- |
| Foo      | [Bar][referenceLink] |

[referenceLink]: https://www.google.com
  `;
  const html = marked(md);
  expect(html).toBe(`<table>
<thead>
<tr>
<th>Column 1</th>
<th>Column 2</th>
</tr>
</thead>
<tbody><tr>
<td>Foo</td>
<td><a href="https://www.google.com">Bar</a></td>
</tr>
</tbody></table>
`);
```

and a quick `git bisect` looks like it was introduced with https://github.com/markedjs/marked/pull/2124

**Comment by willeastcott** [comment]
The PlayCanvas Developer Site was just affected by this too. We recently upgraded marked and all reference style links in markdown tables stopped working (without us noticing at first). I have now [switched them all](https://github.com/playcanvas/developer.playcanvas.com/pull/384) to inline links.  So while we're OK after this fixing up, it'd be great to get reference style links in tables working again.
