### ISSUE TITLE
Paragraph tokens getting ruined when using a Marked extension

### ISSUE THREAD

**Issue by danzool** [markedjs/marked#2589]
**Marked version:**
4.1.0

**Describe the bug**
I am looking to use `marked` on a piece of markdown text to essentially "walk" the tokens and produce a transform of paginated output. This works great for all the built-in token types, but I need to add my own extension to recognize a new custom token so I can inject some non-markdown primitive in my application, in place of that token. For example:

```
# Some heading
Some paragraph
???
a bunch of normal markdown tokens in here
???
```

I would expect to get block tokens of type: {heading}, {paragraph}, and {myCustomItem}, where the first two are identical to what I would get by iterating through tokens without my extension.. However, I am seeing my paragraphs getting trashed and instead producing paragraph tokens that have spaces inserted after each character.

To me, it seems quite unexpected that my extension would have such a side-effect on the standard paragraphs that are not captured by the extension regex.

Here is my extension:

```
export const itemExtension = {
  name: 'myCustomItem',
  level: 'block',
  start(src: string) { return src.match(/\\?\\?\\?/)?.index; },
  tokenizer(src: string, _tokens: any[]) {
    const rule = RegExp('^\\?\\?\\?(.+?)(?:\\?\\?\\?)', 'gs');
    const match = rule.exec(src);
    if (match) {
      return {            
        type: 'myCustomItem',
        raw: match[0],
        text: match[1].trim()
      };
    } else {
      return false;
    }
  },
  renderer (token: any) {
    // I don't care about this since I am going to strip out this token as I walk the tokens.
    return `<p>${token.text}</p>\n`;
  }
};
```

**Comment by calculuschild** [comment]
I suspect your RegEx is not doing what you think it's doing. My guess is the double `\\` backslash escapes are causing your regex match `\` between zero and one times, three times, followed by one character `.+?`. This pattern matches *every single character* which is why it is eating your whole input text one-by-one.  See https://regex101.com/r/Xi3KTu/1. I think you mean to match three question marks: https://regex101.com/r/UHjbZf/1

I know backslashes act differently when writing the Regex in a string vs a Regex literal, so you may need three backslashes in your `const rule` line.

**Comment by danzool** [comment]
Thank you for the response! You were right on the money with the regex being the issue. I couldn't get it to work with 1 backslash—it yields a "Nothing to repeat" error—but this did the trick:

```
RegExp('^\\?{3}(.+?)(?:\\?{3})', 'gs');
```

Thanks again, I'll close this out.
