### ISSUE TITLE
HTML elements / tags in markdown will not be overwritten by renderer

### ISSUE THREAD

**Issue by Charow0206** [markedjs/marked#2650]
**Marked version:** 4.2.1

**Describe the bug**
Not sure if it's me not knowing how to do it correctly, but I noticed HTML tags in markdown are not being overwritten by the renderer. 

For example if I write a blockquote in markdown like this, it will be overwritten:
```> Lorem ipsum ```

but do I write it HTML in it like this, it will not be overwritten:
```<blockquote>Lorem ipsum</blockquote>```

The code: 
```
export const Markdown = (props: MarkdownParserProps) => {
    const renderer = new marked.Renderer();

    renderer.blockquote = (quote) => `<blockquote className="quote">${<Icon name={"bell"} />} ${quote}</blockquote>`;

    const markdown = marked(value, { 
        renderer: renderer
    });

    return (
        <article className="rich-article">
            <div dangerouslySetInnerHTML={{ __html: markdown }} />
        </article>
    );
};
```

**Expected behavior**
I would assume both ways of writing would trigger the override. But it seems like it's not happening, the classname and Icon component for example are only visible on the first blockquote that is created by `>`. The classname and Icon component are not displayed when you write `<blockquote>`.

**Comment by UziTech** [comment]
`<blockquote>Lorem ipsum</blockquote>` will be picked up by the `html` renderer because it is an HTML token not a block quote token. 

[demo](https://marked.js.org/demo/?outputType=lexer&text=%3E%20Lorem%20ipsum%0A%0A%3Cblockquote%3ELorem%20ipsum%3C%2Fblockquote%3E%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

**Comment by Charow0206** [comment]
> `<blockquote>Lorem ipsum</blockquote>` will be picked up by the `html` renderer because it is an HTML token not a block quote token.
> 
> [demo](https://marked.js.org/demo/?outputType=lexer&text=%3E%20Lorem%20ipsum%0A%0A%3Cblockquote%3ELorem%20ipsum%3C%2Fblockquote%3E%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

It seems like that works, but I meant the override doesn't work like I thought it would. For example I tried to override the blockquote like this:
```renderer.blockquote = (quote) => `<blockquote className="hello-world">${quote}</blockquote>`;```

In this case I would assume that every blockquote will receive the class(Name) `hello-world`, but it doesn't. Only the blockquote that are written like ` > lorem ipsum` will receive the class(Name). Blockquotes that are written like `<blockquote> lorem ipsum </blockquote>` will NOT receive the className.

(Keep in mind that I use a blockquote here as example, it's the same for hyperlinks etc.)

**Comment by UziTech** [comment]
> Only the blockquote that are written like `> lorem ipsum` will receive the class(Name). Blockquotes that are written like `<blockquote> lorem ipsum </blockquote>` will NOT receive the className.

That is how it should be because `<blockquote> lorem ipsum </blockquote>` is not a markdown blockquote. It is a markdown HTML block.

**Comment by Charow0206** [comment]
> > Only the blockquote that are written like `> lorem ipsum` will receive the class(Name). Blockquotes that are written like `<blockquote> lorem ipsum </blockquote>` will NOT receive the className.
> 
> That is how it should be because `<blockquote> lorem ipsum </blockquote>` is not a markdown blockquote. It is a markdown HTML block.

Fair enough, I had hoped I could override both, because you can write them both ways in markdown of course. But I don't think there is a native way for that, right?

**Comment by UziTech** [comment]
> But I don't think there is a native way for that, right?

No because in markdown they are two very different things. The rules for handling HTML and blockquotes are very different in markdown. For example text inside html is not parsed as markdown so `lorem *ipsum*` will output `lorem *ipsum*` in an html block but a blockquote block would output `lorem <em>ipsum</em>` ([demo](https://marked.js.org/demo/?text=%3E%20lorem%20*ipsum*%0A%0A%3Cblockquote%3Elorem%20*ipsum*%3C%2Fblockquote%3E&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)).

If you want to read more about the rules of markdown I would recommend reading the [CommonMark spec](https://spec.commonmark.org/current/). These are the rules that all markdown parsers follow (for the most part).

**Comment by Charow0206** [comment]
> > But I don't think there is a native way for that, right?
> 
> No because in markdown they are two very different things. The rules for handling HTML and blockquotes are very different in markdown. For example text inside html is not parsed as markdown so `lorem *ipsum*` will output `lorem *ipsum*` in an html block but a blockquote block would output `lorem \<em\>ipsum\</em\>` ([demo](https://marked.js.org/demo/?text=%3E%20lorem%20*ipsum*%0A%0A%3Cblockquote%3Elorem%20*ipsum*%3C%2Fblockquote%3E&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)).
> 
> If you want to read more about the rules of markdown I would recommend reading the [CommonMark spec](https://spec.commonmark.org/current/). These are the rules that all markdown parsers (are supposed to) follow (for the most part).

That is helpful! Appreciate your response. I’ll close the issue as it works as intended
