### ISSUE TITLE
Dynamic data rendering with code block creates a flickering in dom

### ISSUE THREAD

**Issue by francissebin-2hats** [markedjs/marked#2751]
**Marked version:**
4.2.12
**Describe the bug**
Dynamic data rendering with code block creates a flickering in the dom.

**To Reproduce**

1. [Marked Demo](https://marked.js.org/demo/?text=%60%60%60js%0Aconst%20hello%20%3D%20%27world%27%3B%0A%60%60%60&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

consider if the code block mentioned in the above link is inside a variable and the content is printing one by one. (you can reproduce this by typing a code block in this demo link) you can see a dom flickering issue because it is printing P tag first then after each new line it change to code block.

**Expected behavior**
It should work without any dom issue

**Comment by UziTech** [comment]
Can you show a video of this behavior? I don't see it flickering.

**Comment by UziTech** [comment]
I see the issue. Fenced code blocks currently require a newline at the end of the markdown if there are no closing ticks. This should be fixed by #2756

[marked demo](https://marked.js.org/demo/?text=%60%60%60%0Ademo&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=4.2.12)
[commonmark demo](https://spec.commonmark.org/dingus/?text=%60%60%60%0Ademo)

**Comment by francissebin-2hats** [comment]
Thankyou, I hope it will be merged soon
