### ISSUE TITLE
CLI deprecation warning

### ISSUE THREAD

**Issue by tborychowski** [markedjs/marked#2797]
## Marked version
5.0.1

## Describe the bug
Since the last upgrade (from v4.x to 5.0.1) I'm seeing the following warnings:
```
marked(): mangle parameter is deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-mangle.
marked(): headerIds and headerPrefix parameters are deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-gfm-heading-id.
```

I don't use the js API, just run the CLI via npm scripts.

## To Reproduce
This is the command I use: `marked --gfm -i CHANGELOG.md -o changelog.html`

## Expected behavior
No warnings :-)

**Comment by UziTech** [comment]
In the release notes for [v5.0.1](https://github.com/markedjs/marked/releases/tag/v5.0.1) it explains why and what you can do about it.

**Comment by UziTech** [comment]
Ya we tried to keep the warnings short.

**Comment by calculuschild** [comment]
Do you mind if I make a PR to add those extra words? I think it might be worth the added length if it gives our users a more clear indication of what's going on.

**Comment by UziTech** [comment]
Sounds good to me. 👍

**Comment by danielkrajnik** [comment]
How do you configure it so --no-mangle option is used by default? I've tried setting this option to false in src/default.js, but it didn't seem to pick it up on subsequent invocations.

**Comment by tborychowski** [comment]
@danielkrajnik 
I use marked as CLI in `scripts` of my `package.json`, so I have sth like this:

```json
"scripts": {
    "changelog": "marked --no-mangle --no-header-ids --gfm -i CHANGELOG.md -o docs/changelog.html"
}
```

**Comment by tborychowski** [comment]
can you not just add an alias in your shell? e.g.

```sh
alias md='marked --no-mangle --no-header-ids --gfm -i '
```

then you'd just use this like this:
```sh
md page.md -o page.html
```

**Comment by danielkrajnik** [comment]
You are right that this would work, putting it in .profile or /etc/profile would ensure that other programs would pick it up as well, but I hoped that npm had a dedicated place for these changes. It would make it easier to maintain it later on, because normally you expect all program-specific configuration to live inside .config, /etc or other standard locations. .bashrc/.zshrc is normally used only for "personal customisations" and this seems to be part of "application logic".

**Comment by romgrk** [comment]
Just to note, the deprecation warnings are so disruptive that upgrading to latest marked version made a CLI tool I'm using unusable. It was used for validation & error reporting, and now all I see is a wall of marked deprecation warnings. A minor version upgrade shouldn't cause this kind of behavior. If I'm going to need to make a change to my codebase, I'd rather just have to do it at the major version release rather than needing to do it at a minor version release.

**Comment by UziTech** [comment]
@danielkrajnik PRs are always welcome 😁👍
