### ISSUE TITLE
can marked support node 14?

### ISSUE THREAD

**Issue by hqqxxf** [markedjs/marked#3059]
**Describe the feature**
marke support node >= 14

**Why is this feature necessary?**
because our old project is only support node 14，so I hope marked can support node >= 14

**Describe alternatives you've considered**
if not, What API does marked use that can only be used on node 16 or above?

**Comment by UziTech** [comment]
I don't know if it can support node 14. you can try it and see if there are any errors. But marked is not going to support obsolete node versions. We will be dropping support for node v16 soon since node doesn't support it any more.

You can use babel to compile marked to work with whatever version of node you want.

**Comment by calculuschild** [comment]
@UziTech We have started getting a lot of similar issues that point to needing Babel. My understanding is for bundlers like webpack / browserify / etc., the expected practice is to minimize the number of files being compiled, so they exclude `/node_modules` by default (or at least encourage not running Babel over all your dependencies). I.e., they generally expect that Babel is applied at the npm package, not by the consumer.

Would it make sense to have Marked use Babel so it can provide a working version for older browsers and function correctly with bundlers out of the box?

**Comment by UziTech** [comment]
Babel will slow down marked and increase the download size by a lot, which is why we stopped using it and moved to only support certain versions of node.

If someone wants to stay on an old insecure version of node I don't think it is unreasonable to ask them to stay on an old insecure version of marked as well. Or do the work themselves to transpile with Babel
