### ISSUE TITLE
Bold hyper link with two * symbols causes one to be visible after parsing and removes space

### ISSUE THREAD

**Issue by iKingNinja** [markedjs/marked#3069]
**Marked version: 9.1.4**

**Describe the bug**
Writing bold hyper links with two * symbols results in the last symbol being visible and also removes the space between the last * symbol and the next character.

**To Reproduce**

- Use marked from jsdelivr

```html
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
    marked.parse("**[🤖┃bot-commands](https://discord.com/channels/870575002536280074/981392899012980796)** hello") // Output: <strong><a href="https://discord.com/channels/870575002536280074/981392899012980796">🤖┃bot-commands</a>*</strong> | rendered: 🤖┃bot-commands*hello
</script>
```

Rendered result:
![image](https://github.com/markedjs/marked/assets/83887130/963532bf-df83-4bed-97fb-d0af209ff67c)

**Expected behavior**
The parser should not include the last * symbol in the output which means the result should be <strong><a href="https://discord.com/channels/870575002536280074/981392899012980796">🤖┃bot-commands</a></strong>

**Comment by UziTech** [comment]
Should be fixed in #3070 
[demo](https://marked-website-git-fork-uzitech-fix-emstrong-unicode-markedjs.vercel.app/demo/?text=**%5B%F0%9F%A4%96%E2%94%83bot-commands%5D%28https%3A%2F%2Fdiscord.com%2Fchannels%2F870575002536280074%2F981392899012980796%29**+hello&options=%7B%0A+%22async%22%3A+false%2C%0A+%22breaks%22%3A+false%2C%0A+%22extensions%22%3A+null%2C%0A+%22gfm%22%3A+true%2C%0A+%22hooks%22%3A+null%2C%0A+%22pedantic%22%3A+false%2C%0A+%22silent%22%3A+false%2C%0A+%22tokenizer%22%3A+null%2C%0A+%22walkTokens%22%3A+null%0A%7D&version=master)
