### ISSUE TITLE
Task List, Unordered List and Blockquote Bugs, along with Suggestions for Improvement

### ISSUE THREAD

**Issue by jiaopengzi** [markedjs/marked#3119]
# marked : 11.0.0

Hello, among the many Markdown parsing libraries, I find your library more outstanding.

Today I discovered two bugs.

## Bug 1

When unordered lists and task lists are used together, they are combined into one list. I think this is incorrect. There should be two separate lists.

```markdown
- ul list1
- ul list2
- [x] task list1
- [ ] task list2
```

- Image 1: Bug 1 - HTML output from marked parsing
![image](https://github.com/markedjs/marked/assets/52224629/4bf3a003-c5a1-40b5-87a7-92ae098c86c5)

- Image 2: Bug 1 - HTML source code from marked parsing
![image](https://github.com/markedjs/marked/assets/52224629/9fa68ae5-29d3-496e-b7a3-865b3931a9bf)

- Image 3: Bug 1 - Output from Typora parsing
![image](https://github.com/markedjs/marked/assets/52224629/c0a5d2ac-ffdf-41ab-ab34-334fae6565a3)

## Bug 2

When using blockquotes, the Markdown text has already moved to a new line, but the parsed text is still in one paragraph with no line break, only a space in between. I believe this is also incorrect.

```markdown
> blockquote1
> blockquote2
> blockquote3
```

- Image 4: Bug 2 - HTML output from marked parsing
![image](https://github.com/markedjs/marked/assets/52224629/9e355d80-2be8-45db-bff8-93d9414018e8)

- Image 5: Bug 2 - HTML source code from marked parsing
![image](https://github.com/markedjs/marked/assets/52224629/0b061f57-278a-4a01-9cf2-4cadc06f20c4)

- Image 6: Bug 2 - Output from Typora parsing
![image](https://github.com/markedjs/marked/assets/52224629/68af9a3d-1c7a-4880-8746-1f7641626d50)

In addition, I have a small suggestion. In my opinion, the task list should have all the necessary markers; otherwise, its style is quite troublesome. Although it can be extended, I feel it's not the most elegant solution. I have also referred to this discussion: https://github.com/markedjs/marked/issues/1430. I hope the author can offer support. Thank you very much for your attention.

**Comment by UziTech** [comment]
Thank you for loving marked 🥰

By default marked tries to follow [GFM](https://github.github.com/gfm/) and [CommonMark](https://spec.commonmark.org/0.30/) spec.

## Bug 1

As you can see by the following example GitHub uses a single list for task and non-task items:

- item1
- [ ] item2

Changing this would mean markdown in marked wouldn't render like GitHub.

## Bug 2

This follows CommonMark: [demo](https://spec.commonmark.org/dingus/?text=%3E%20blockquote1%0A%3E%20blockquote2%0A%3E%20blockquote3)

You can get this to work if you set the `breaks` [option](https://marked.js.org/using_advanced#options) to `true`.  That option will add a `<br>` for every newline like GitHub comments.

## styling

Marked renders html without styling or classes. It is up to the user to provide styling and ideally markdown should render semantic html simple enough to style without classes.

## extensions

We have tried to make [extending marked](https://marked.js.org/using_pro#extensions) as easy as possible. Extensions are a way for users to opt-in to certain features instead of requiring everyone to download code they don't need/want. If you create an extension to add classes to task lists or separate task lists from non-task lists feel free to add it to the [known extensions](https://marked.js.org/using_advanced#extensions) in our docs.

Thanks again!

**Comment by jiaopengzi** [comment]
Thank you very much for your prompt response. Indeed, using semantic tags is better. I now understand your original intention, and I have gained a lot of valuable insights. I've also learned about creating custom renderers to implement CSS class names.
I sincerely thank you once again.
