### ISSUE TITLE
Unexpected behavior when using `marked.lexer` or `new marked.Lexer`

### ISSUE THREAD

**Issue by poirierlouis** [markedjs/marked#3316]
**Marked version:** v12.0.2

**Describe the bug**
Behavior is immutable (A) when using `marked.lexer` but it is somehow mutable (B) when using `new marked.Lexer().lex()`.

I'm using instance of a Lexer to call `lex()` with Markdown data and get tokens. When reusing the same instance, and calling `lex()` with different Markdown data, it returns the same tokens of the first call. This is not expected, or at least it is not [documented](https://github.com/markedjs/marked/blob/master/docs/USING_PRO.md#access-to-lexer-and-parser).

**To Reproduce**

1. See [Stackblitz](https://stackblitz.com/edit/marked-lexer-issue?file=src%2Fmain.ts) example (scroll at the end of `main.ts`).
2. Click option A, it shows unique content for car and plane.
2. Click option B, it shows unique content for car, but car + plane in second case.

**Expected behavior**
I would expect `lex()` to only work with the Markdown data used in method call. I wouldn't expect data from previous calls to pop in the returned value.

`marked.lexer` is a good candidate as a workaround. But maybe it is made like this by design? If so, it would be great to inform users about this in documentation.

**Comment by UziTech** [comment]
You are correct. The lex method on an instance of Lexer does not reset the tokens before tokenizing the string that is passed in. I'm not sure if this was intentional but it seems like that is the way it has been since before v1.0.0.

I don't see any reason to change it since there could be someone using it to parse small markdown parts instead of the whole thing.

If you want to update documentation for this that would be much appreciated 😁👍
