### ISSUE TITLE
Url generate code 

### ISSUE THREAD

**Issue by qqaimh** [markedjs/marked#3452]
**Marked version: 14.1.2

**Describe the bug**
Below text:
"https://github.com/dpfried/lm-evaluation-harness/。"
Generate  code:
`<a href="https://github.com/dpfried/lm-evaluation-harness/%E3%80%82">https://github.com/dpfried/lm-evaluation-harness/。</a>`
Show in browser:
<a href="https://github.com/dpfried/lm-evaluation-harness/%E3%80%82">https://github.com/dpfried/lm-evaluation-harness/。</a>

**Expected behavior**
Below text:
"https://github.com/dpfried/lm-evaluation-harness/。"
Generate  code:
`<a href="https://github.com/dpfried/lm-evaluation-harness/">https://github.com/dpfried/lm-evaluation-harness/</a>。`
Show in browser:
<a href="https://github.com/dpfried/lm-evaluation-harness/">https://github.com/dpfried/lm-evaluation-harness/</a>。

**Comment by UziTech** [comment]
As you can see with your text above we generate the same code as GitHub. This is because `。` is not an approved punctuation to end an autolink.

You can use angle brackets to tell marked and GitHub where the link starts and ends. [Gfm spec](https://github.github.com/gfm/#autolinks-extension-)

`"<https://github.com/dpfried/lm-evaluation-harness/>。"`


"<https://github.com/dpfried/lm-evaluation-harness/>。"
