### ISSUE TITLE
Link with underscores and parantheses wrapped in underscores is parsed incorrectly

### ISSUE THREAD

**Issue by Brakebein** [markedjs/marked#3468]
**Marked version:** 14.1.2

**Describe the bug**
A link is not parsed correctly if it contains underscores and parantheses, and is itself wrapped with underscores (e.g. for styling italics).
Pattern: `_[Link title](https://domain.org/link_with_underscores_(parantheses))_`

**To Reproduce**
Open Marked demo link. In CommonMark Demo it is displayed correctly.

1. [Marked Demo](https://marked.js.org/demo/?text=Link%20is%20**not**%20parsed%20and%20rendered%20correctly%3A%20_%5BSeven%20wonders%5D(https%3A%2F%2Fde.m.wikipedia.org%2Fwiki%2FSieben_Wunder_(Jena))_%20some%20more%20text%0A%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.2)
2. [CommonMark Demo](https://spec.commonmark.org/dingus/?text=Link%20is%20**not**%20parsed%20and%20rendered%20correctly%3A%20_%5BSeven%20wonders%5D(https%3A%2F%2Fde.m.wikipedia.org%2Fwiki%2FSieben_Wunder_(Jena))_%20some%20more%20text)

**Expected behavior**
Only (interactive) link title should be displayed with italics/bold styling (see CommonMark demo).

**Comment by UziTech** [comment]
Looks like this is because of the way we parse the strong\em we need to try to make sure the end is not inside a link

The workaround is to use `*` for the italics. [Demo](https://marked.js.org/demo/?text=Link%20is%20**not**%20parsed%20and%20rendered%20correctly%3A%20*%5BSeven%20wonders%5D(https%3A%2F%2Fde.m.wikipedia.org%2Fwiki%2FSieben_Wunder_(Jena))*%20some%20more%20text%0A%0A&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.2)
