### ISSUE TITLE
Cannot correctly escape closing `~`

### ISSUE THREAD

**Issue by mjbvz** [markedjs/marked#3516]
**Marked version:** 14.1.3

**Describe the bug**
Cannot use `\` to escape `~`

**To Reproduce**

```md
*a\* ~b\~
```

https://marked.js.org/demo/?outputType=html&text=*a%5C*%20~b%5C~&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=14.1.3

**Expected behavior**
This should result in `*a* ~b~` being rendered as text instead of markup 

Instead we get:

```html
<p>*a* <del>b\</del></p>
```

Works for the `*` and also seems to work if the opening `~` is escaped instead of the closing one

**Comment by UziTech** [comment]
Yup this is a gfm only element. It should output:

*a\* ~b\~

**Comment by UziTech** [comment]
This should be fixed by #3517 ([demo](https://marked-website-git-fork-uzitech-escape-del-markedjs.vercel.app/demo/?text=*a%5C*%20%7Eb%5C%7E&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=master))
