### ISSUE TITLE
[bug]inline code cannot be fully parsed

### ISSUE THREAD

**Issue by fanybook** [markedjs/marked#3543]
**Marked version:**
15.0.2 & 14.1.2

**Describe the bug**
inline code cannot be fully parsed

example:
```markdown
# TODO 2024-11-06

1. Level01

   > `electron` 666
   >
   > 1. `wow` 777

   1. Level02-1

      `did-start-navigation` 666

   2. Level02-2

      `contents.navigationHistory` 666

2. 。。。
```

**Comment by UziTech** [comment]
You haven't stated what the actual problem is with that markdown. It seems to look fine to me in the [demo](https://marked.js.org/demo/?text=%23%20TODO%202024-11-06%0A%0A1.%20Level01%0A%0A%20%20%20%3E%20%60electron%60%20666%0A%20%20%20%3E%0A%20%20%20%3E%201.%20%60wow%60%20777%0A%0A%20%20%201.%20Level02-1%0A%0A%20%20%20%20%20%20%60did-start-navigation%60%20666%0A%0A%20%20%202.%20Level02-2%0A%0A%20%20%20%20%20%20%60contents.navigationHistory%60%20666%0A%0A2.%20%E3%80%82%E3%80%82%E3%80%82&options=%7B%0A%20%22async%22%3A%20false%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22extensions%22%3A%20null%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22hooks%22%3A%20null%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%0A%7D&version=15.0.2)

**Comment by fanybook** [comment]
@UziTech I have found the reason

        const renderer = new marked.Renderer()
        
        // it was caused by this, how can i fix it?
        renderer.text = (token) => {
            return token.text
        }

**Comment by fanybook** [comment]
added log
```js
        renderer.text = (token) => {
            console.log(666.111, token.type, token.raw)
            return token.raw
        }

        renderer.codespan = (token) => {
            console.log(666.112, token.type, token.raw)
            return token.raw
        }
```

outputs
```bash
666.111 text TODO 2024-11-06
666.111 text Level01
666.111 text Level01
666.112 codespan `electron`
666.111 text  666
666.111 text `wow` 777
666.111 text Level02-1
666.111 text Level02-1
666.111 text `did-start-navigation` 666

666.111 text `did-start-navigation` 666

666.111 text Level02-2
666.111 text Level02-2
666.111 text `contents.navigationHistory` 666
666.111 text `contents.navigationHistory` 666
666.111 text 。。。
666.111 text 。。。
```

**Comment by fanybook** [comment]
i known how do it

        const renderer = new marked.Renderer()

        const rawTextHandler = renderer.text
        renderer.text = function(token) {
            if (!('tokens' in token && token.tokens) && ('escaped' in token && token.escaped)) {
                return 'a string'
            }

            return rawTextHandler.apply(this, [token])
        }

**Comment by Yuezi32** [comment]
I got the same issue.

```
const md = '1. **BOLD** aaa'

const rendererRefToHref = {
    text(token) {
        return token.text
    }
}

marked.use({ renderer: rendererRefToHref })

marked.parse(md)
```
Then, the output is：
```
1. **BOLD** aaa
```
The text "BOLD" is NOT bolded.

**Comment by UziTech** [comment]
You can see how to do it in marked's renderer

https://github.com/markedjs/marked/blob/152175615c52ff4cb59a1e8dd7a353d362180280/src/Renderer.ts#L211-L215
