### ISSUE TITLE
the backslash should be transferred to '\\' exclude in code tag

### ISSUE THREAD

**Issue by AmosJin** [markedjs/marked#775]
`\ -> \\`
when I used like `marked('\\dir')`, the output now is `<p>\\dir<p>`, but in HTML, it appears just like `<p>\dir</p>`

**Comment by Feder1co5oave** [comment]
Take into account that in Javascript string literals backslashes need to be escaped. So if you want a double backslash you need to write `'\\\\dir'`.

**Comment by AmosJin** [comment]
I know that, what I mean is the `marked` should solve this in `code` tag, other tags isn't necessary. For example, if escape all `\` -> `\\`, the html in `code` tag will be strange, like `\\dir` -> `\\\\dir`.

**Comment by Feder1co5oave** [comment]
close @joshbruce

**Comment by joshbruce** [comment]
```
\\dir
```

**Comment by joshbruce** [comment]
Think there might be something to this. Code blocks are a different beast near as I can tell. Not sure how to resolve using regex though.

**Comment by UziTech** [comment]
this seems to be fixed in the latest version of marked. [demo](https://marked.js.org/demo/?text=%60%5C%5Cdir%60&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20false%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D)
